### ISSUE TITLE
Paladins and Rangers can't memorize spells

### ISSUE THREAD

**Issue by ARMELIUS** [GrognardsFromHell/TemplePlus#100]
Paladins and Rangers can't memorize spells. They disappear on rest.

**Comment by DudeMcDude** [comment]
Thanks for reporting, and welcome!

**Comment by DudeMcDude** [comment]
Ok, the issue seems to be with Paladins/Ranger at level 4 or 5 only get a 1st level spell slot due to their stat bonus (or level 8 for level 2 spell and so on). Fixed.
