### ISSUE TITLE
Clerics with war domain get every feat

### ISSUE THREAD

**Issue by ARMELIUS** [GrognardsFromHell/TemplePlus#101]
Rolling a cleric ~~of Hextor~~ with the War domain gets you every feat.

**Comment by shartte** [comment]
That certainly is an interesting issue. Paging @DudeMcDude. Probably one for you?

**Comment by DudeMcDude** [comment]
Aye, will check it out!

**Comment by DudeMcDude** [comment]
Fixed. Thanks for reporting!

**Comment by ARMELIUS** [comment]
Wow, that was fast.

Great project, guys. Thank you for your efforts, they are appreciated.
