### ISSUE TITLE
Check for DLL Compatibility on Startup

### ISSUE THREAD

**Issue by shartte** [GrognardsFromHell/TemplePlus#102]
When TemplePlus starts up, we should check if the Temple DLL we're about to load is compatible with us, by (for example) comparing the checksum against checksums we know.

Right now the following DLL versions are compatible:
* Patch 3
* Moebius (GoG version)
* Co8

The ToEE Frontend application seems to modify the DLL file on disk for certain settings, so checksumming may be a non starter. Instead we might want to check certain areas that are not modified for known patterns.

**Comment by DudeMcDude** [comment]
I modified it to just check if the DLL filesize is over 4MB. Good enough for detecting the newer Co8 :P
