### ISSUE TITLE
Lighting applied to portal icon

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#123]
http://i.imgur.com/R9Z6Mvh.png

**Comment by shartte** [comment]
It doesn't look like that for me. This is on Co8. Can you test again with the latest revision?

![2016-02-09 13_37_00-temple of elemental evil temple](https://cloud.githubusercontent.com/assets/1261399/12916373/3813dee2-cf32-11e5-9ba8-6acbf15e3ff9.png)

**Comment by DudeMcDude** [comment]
Was fixed by one of the other issues :)
