### ISSUE TITLE
Some particle systems don't play

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#136]
Example: casting Mage Armor should leave a lasting ring effect, but it doesn't.

Also I think some of the ambient particles in the Moathouse are missing (like one that looks like a dragonfly kind of thing)

**Comment by shartte** [comment]
So I think that the particle systems actually do play, but some of the particles dont render correctly.

Can you check mage armor again? It looks a lot better for me now, after commit 5f3909cd.

**Comment by shartte** [comment]
Okay I think I figured out what the actual issue was (particles spawned at twice the normal rate and led to existing particles being killed after half their lifespan).

Can you check if this fixes it for you? All particle systems now looked better for me.

**Comment by DudeMcDude** [comment]
Yep!
