### ISSUE TITLE
Equipped inventory icons don't replace the background texture

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#139]
The background texture should disappear when an item is equipped (e.g. the sword in the hand slot should go away)

**Comment by DudeMcDude** [comment]
Reference: this is how it should look

![image](https://cloud.githubusercontent.com/assets/11220053/13086979/67d6955e-d4ee-11e5-9a0f-937e16486707.png)


And this is how it looks right now

![image](https://cloud.githubusercontent.com/assets/11220053/13087023/9ab84e9a-d4ee-11e5-81e8-d43011a38ae1.png)

**Comment by shartte** [comment]
Can you recheck this? I think i implemented the missing draw-flag in the commit mentioned above.

**Comment by DudeMcDude** [comment]
Yeah, works!
