### ISSUE TITLE
Cone spell particle effects emit from wrong direction

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#144]
Ex spell: Color Spray

**Comment by DudeMcDude** [comment]
Possibly related: when casting some spells, like Magic Missile and Ray of Frost, it occasionally flashes a particle above the caster for a brief moment.

**Comment by DudeMcDude** [comment]
Ok it looks like cones just calcualte the wrong angle:
![image](https://cloud.githubusercontent.com/assets/11220053/13167703/5b4054f0-d6de-11e5-9515-cc92e6714a40.png)

![image](https://cloud.githubusercontent.com/assets/11220053/13167721/7a769618-d6de-11e5-9bf2-940f0c72d7c1.png)

**Comment by shartte** [comment]
There was a fixed rotational offset that I missed. These should now look correct.
