### ISSUE TITLE
Map tiles occasionally flash to a different time of day state

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#145]
e.g. when you scroll around in Hommlet at night, occasionally one of the sector tiles will flash to the day state tile.

**Comment by shartte** [comment]
Can you check if this is still happening for you now? I couldn't reliably reproduce it (but also got *some* flashes). I optimized the terrain transitioning between day and night a bit and fixed a small inconsistency.

**Comment by DudeMcDude** [comment]
Don't seem to get the flashing anymore, but now it gradually fades to nighttime every time I enter a map (at night) instead of being as nighttime from the getgo.

**Comment by shartte** [comment]
This is *really* odd since it checks the daytime state when you enter the
map. Are we talking entering a map via travelling (with ingame time
advancing) or really just entering/leaving i.e. from a building?

**Comment by DudeMcDude** [comment]
entering / leaving buildings

**Comment by DudeMcDude** [comment]
I think the issue might be that the initial state was "flipped" and then it changes to the correct one.

**Comment by shartte** [comment]
My god it's a stupid mistake in the load function, haha:

mIsNightTime = gameSystems->GetTimeEvent().IsDaytime();
