### ISSUE TITLE
Deployment and update solution for release

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#155]

**Comment by shartte** [comment]
Update for this:

Squirrel.Windows seems like a good bet. 

The updater will be called using Update.exe. An example of the usage can be found in the source code for the Atom text editor: https://github.com/atom/electron/blob/377a8eefb229cbca78866b190015e678b163aff5/lib/browser/api/auto-updater/squirrel-update-win.js

**Comment by shartte** [comment]
Open questions: How do we actually publish the updates. Using github releases might be a good way.

What are the files we need to include in the nuget package to get the Update.exe where it needs to be .

How do we facilitate changing update channels (beta / stable)

**Comment by DudeMcDude** [comment]
1. Github releases sounds good to me.

2. Not sure I understand what you mean.

3. I'm fine with only managing a stable channel, with Beta being downloaded manually.

**Comment by shartte** [comment]
> What are the files we need to include in the nuget package to get the Update.exe where it needs to be .
That is just a technical Squirrel specific question. 

A Beta channel seems easy to do. The only question is where we want to host this. Possibly on bintray? They are free for Open Source.

**Comment by shartte** [comment]
This is now complete
