### ISSUE TITLE
Cloth not attaching to models correctly in character viewer

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#160]
See google drive for comparison shots in the character viewer

**Comment by shartte** [comment]
Which one is the  wrong one and what is it comparing?

**Comment by DudeMcDude** [comment]
Hmm, I guess you can also use the shots from the lighting issue, it's even more obvious there in the object editor.

https://github.com/GrognardsFromHell/TemplePlus/issues/161

**Comment by shartte** [comment]
I have zero idea where this might be coming from to be honest.

Do you have any idea whether this only happens in the paperdoll or also ingame?

**Comment by DudeMcDude** [comment]
In the gameworld I think it's ok, e.g. 

![image](https://cloud.githubusercontent.com/assets/11220053/13432129/06dfc62a-dfd5-11e5-8c65-5a964ef5e03c.png)


Vs. older version:

![image](https://cloud.githubusercontent.com/assets/11220053/13432135/11b4b16e-dfd5-11e5-9dcf-d8e9f7d7aa22.png)
