### ISSUE TITLE
Point lights not lighting correctly

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#161]
Normal:

![image](https://cloud.githubusercontent.com/assets/11220053/13411154/50fd6032-df44-11e5-8c81-24af89b72f9a.png)

Current:

![image](https://cloud.githubusercontent.com/assets/11220053/13411168/62eac9ba-df44-11e5-97d0-f72338ed64a8.png)

**Comment by shartte** [comment]
This is a nice bug report. Only thing missing is a savegame, heh.

But should be easy to reproduce.
