### ISSUE TITLE
Reports of small problems and small suggestions

### ISSUE THREAD

**Issue by Felipefpl** [GrognardsFromHell/TemplePlus#186]
First i wanna thank you for this mod, it's really nice to see something not related to Co8 that fix several annoying things with the game, for me so far what i liked the most is:

1 - Now when i order a character to move in a straght line he goes in a straight line. No strange detours to arrive at a place so far.

2 - The small delay it had when i ordered the character to move is gone, surely the result of your work in the gfx.

3 - No more msg saying TEE stopped working when i close it.

4 - The F9 quick load key now works, it didnt with vanilla and patch 2.

Now i have a few bad things to report (just for the record i never finished the game or even left hommlet so i cant help with problems in other locations) and my specs are: Win7 x64, Intel HD 2000, build 727, patch 2.0 and 4 GB RAM, here it goes:

1 - Temple+ identifies my videocard as primary adapter instead of intel hd graphics like vanilla does, just saying this for the record because i dont know if this can be a problem now or further.

2 - The Home key doesnt put the character in the center of the screen like it should, i have to click 2x in the portrait for that to happen, when i was having the problem reported in the issue 184 even clicking 2x in the portrait didnt put the character in the center of screen, i have no idea if there are other keys with problems so far.

3 - Temple+ auto-selected my resolution as 1280x1024x32 even with my max height being 900 (i have a 20 inch monitor with max resolution = 1600x900) the strange thing is: in the templeplus.ini my resolution is 1024x768 like on vanilla except that in the Vanilla section of Templeplus.ini it reported my color system as 32 bit instead of the 16 bit of the default vanilla. One more thing: 1280x1024 It's the only resolution available, i cant change it.

4 - High quality cloth option isnt kept enabled by templeplus, it is by vanilla TEE.

5 - The party banter (text) option isnt never being kept on by vanilla or templeplus.

I have a few suggestions for the mod, i dont know if they are on the way so sorry if i'm being repetitive. ;) I understand that several of them may not be possible.

1 - Put ALL the dialog boxes at the center of the screen independent of the resolution you're using. The conversation windows could be put at the bottom center of the screen like on Planescape: Torment, it looks better IMHO. ;)

2 - An option to choose the size of the font of those windows (i know these will be HARD to do since it may involve to change the GUI to give room for the bigger fonts) ;)

3 - A way to put the entire map of hommlet (and other places) fully visible in the screen, right now seeing only small pieces of the city while you can the map of the whole world really sucks. The map in my opinion should be a square that occupies a good part of the screen.

4 - You should put a link to download the files here https://github.com/GrognardsFromHell/TemplePlus i only found the right place thanks to the link at rpgcodex and even so i didnt see the link in the signatures of Sitra or Pugmeister (btw DudeMcDude, are you Sitra?)

5 - You should try 7zip to compress the files, i reduced the size to 9,47 MB using the best compression options, i ask for that because i have dialup (and if you think i suck because of this you should see the next request) =P

6 - Is there a way to create an option to make the moving background stuck? I ask because i have a problem with motion sickness and when i create the characters and look at moving background i feel nauseous :/ - i must be the only one or one of few ppl with this problem. x( One or more of the pictures you posted at rpgcodex would make a nice background(s) for the game.

7 - I was thinking if there was a way to remove the mouse scrolling and make the game sort of like neverwinter nights or diablo where the character is always at the center of the screen and when you click anywhere (in the border of the screen for example) the character moves there but the screen doesnt (i think scrolling doesnt make much sense of course the option to scroll will always be there) ;)

That's all, thank you very much for your work with the mod and for your attention.

**Comment by DudeMcDude** [comment]
Hi Felipe, thank you for the suggestions. The GUI will be the focus of the next release, and some of your suggestions might make it in ;)

Regarding the resolution, the relevant setting is actually renderWidth and renderHeight. Are these set at 1600 and 900? 

Note that the ingame options menu is currently not reflective of the actual resolution used. On that note, High Quality Cloth doesn't actually do anything. Banter text is indeed bugged, there's a mixup in loading /assigning the definitions.

**Comment by Felipefpl** [comment]
"Hi Felipe, thank you for the suggestions. The GUI will be the focus of the next release, and some of your suggestions might make it in ;)"

Cool, nice to know that.

"Regarding the resolution, the relevant setting is actually renderWidth and renderHeight. Are these set at 1600 and 900?"

They are set like this: renderHeight=900 and renderWidth=1600

"Note that the ingame options menu is currently not reflective of the actual resolution used. On that note, High Quality Cloth doesn't actually do anything."

I see, i wonder what is the resolution being used then. Regarding cloth i wonder why this option was left in the settings. Aside banter text the other problems happen with you?

**Comment by DudeMcDude** [comment]
The resolution used is what's denoted in renderHeight and renderWidth (i.e. 1600x900, as it should be). If you want to change this, you should change these settings.

As for High Quality Cloth, I don't know why it was included, but it's hardly unusual for ToEE - we've seen various mismatches of that sort, possibly from last minute changes. Same goes for Banter Text (it looks like there's an offset in the config reader). 

I can confirm the Home key issue, will fix.

Oh and btw yes, I'm Sitra Achara.

**Comment by Felipefpl** [comment]
"The resolution used is what's denoted in renderHeight and renderWidth (i.e. 1600x900, as it should be). If you want to change this, you should change these settings."

I see, i changed it to 1440x900, it seems to have worked but the Options GUI still displays the 1280x1024 resolution as the only one available, surely a bug. ;) Btw, i tried the 1280x720 and it didnt work well, the GUI, fonts and the appearance of the entire game was ugly, i didnt try the other ones, maybe the result is the same? I'll see later.

"As for High Quality Cloth, I don't know why it was included, but it's hardly unusual for ToEE - we've seen various mismatches of that sort, possibly from last minute changes. Same goes for Banter Text (it looks like there's an offset in the config reader)."

Strange indeed, they should have given more time for the development, good that the banter text bug was confirmed.

"Oh and btw yes, I'm Sitra Achara."

I thought so. :)
