### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#188]
Concentrating fan feedback here

* It would be cool in chargen if we could right-click the attribute values instead of dragging them to the empty field.

**Comment by Felipefpl** [comment]
Talking about UI i see now that Temple Plus requires .NET 4.0 to work, will this be the way it's gonna work now? .NET is one of the things that turn me off about Co8 for example, why not using the native GUI from windows instead?

**Comment by DudeMcDude** [comment]
I think you got that mixed up with Java? That's what Co8 uses for the front end (and yeah, it's horrible).

**Comment by Felipefpl** [comment]
i remember an old version of Co8 using .NET as a frontend for the mod, i dont know anything about the new versions though.
