### ISSUE TITLE
Wonnilon's chest causing crash

### ISSUE THREAD

**Issue by pelador** [GrognardsFromHell/TemplePlus#191]
Two times in a row I attempt to open Wonnilon's chest on the first floor of the temple and two times in a row I got the same crash.

**Comment by shartte** [comment]
Hi, can you provide a logfile / crashdump for this crash?

**Comment by pelador** [comment]
No dump file created but here's a log. 

[TemplePluslog.zip](https://github.com/GrognardsFromHell/TemplePlus/files/191983/TemplePluslog.zip)

I can unlock the chest but as soon as I try to open it gives me a runtime error.

**Comment by DudeMcDude** [comment]
Oh wow, that's an ancient build hehe (660).
This bug has been fixed in one of the newer versions. (the model attachment to particle system bug)

Temple+ will be officially released this Friday, complete with an auto-updater. If you don't want to wait until then, you can download build 748.
