### ISSUE TITLE
Improve Co8 handling

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#202]
- If users install Temple+ first and then Co8 - need to set the "usingCo8" flag
- NC vs. Standard edition (flag 500)

**Comment by shartte** [comment]
> NC vs. Standard edition (flag 500)
What is that about?

**Comment by shartte** [comment]
The first part is fixed by b87c745

**Comment by shartte** [comment]
Added a check for Co8 DLL without Co8 data files in the configuration utility (8e0ee70)

**Comment by DudeMcDude** [comment]
Co8 differentiates between NC and Standard editions of the modpack by setting game.global_flags[500] in py00334generic_spawner.py (NC is with the flag set to 1). I used the NC version of the file there, which converts the Standard to NC. Not a huge deal since the Co8 content only affects the post-endgame stage, but it needs fixing. (ideally this would be solved by just making a combined download, but yeah..)

**Comment by shartte** [comment]
Hm we should probably split this issue then, since one part is already done and the second part doesnt seem to have much to do with the first, heh.
