### ISSUE TITLE
Animation slot got borked

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#210]
https://drive.google.com/open?id=0BzF5KfpDewVYTjA0Tkk0c0ZFRU0

Apparently this happens after a character recovers from paralysis.

**Comment by shartte** [comment]
This seems to be related to the anim_priv system and not AAS though. I checked the save and the idle animation is actually playing. Animation slot 2 is assigned to the priest that doesn't move on-click. Using the immediate window i was also able to get that anim slot id for the handle.

I dont see any errors when trying to move the character thouhg, but its possible that pushing a goal for the char is borked.

**Comment by shartte** [comment]
You can get some info on the anim slots by breaking on PyGame_GetHovered and typing into the immediate window:
```
animAddresses.slots[2]
```

**Comment by shartte** [comment]
So apparently the character still has a running goal that doesn't finish?

```
0x118d3e80 {{goalType=ag_anim_idle (0x00000002) unk1=0x77df3e98 self={obj=0x09d7b3f000000cdb location=...} ...}, ...}
    [0x00000000]: {goalType=ag_anim_idle (0x00000002) unk1=0x77df3e98 self={obj=0x09d7b3f000000cdb location={location=...} ...} ...}
    [0x00000001]: {goalType=ag_throw_spell_w_cast_anim_2ndary (0x0000004d) unk1=0x00000000 self={obj=0x09d7b3f000000cdb ...} ...}
```
