### ISSUE TITLE
Crashing upon initiating a random encounter

### ISSUE THREAD

**Issue by TheMadSword** [GrognardsFromHell/TemplePlus#212]
Hi,

I often crash when having a random encounter. In this recent crash, I first had a random encounter. I then lost one of my character (the rogue, game.party[1]), which made me reload my save game. I then tried once more to find a random encounter, which crashed the game.

The first random encounter had 2 sea hags (one was alive at the end, when my rogue died), 2 water snake and 2 birds (Kapocinth I guess, one was alive at the end, when my rogue died). I crashed before being able to see the 2nd random encounter. No crash dump was generated. By looking at the log, I find strange to see so many different kind of enemy destroyed (also there is trolls, and they usually only hang with themselves)

I'm also unsure what to think of the shitload of errors ("[core] [error] Unable to register texture", and the "[core] [error] Unable to load MDF file").

[TemplePlus.log.txt](https://github.com/GrognardsFromHell/TemplePlus/files/201427/TemplePlus.log.txt)

**Comment by DudeMcDude** [comment]
Thanks, the log was very helpful. (I see that you found it eventually?)

The texture errors are unrelated and harmless, they just indicate there's no texture for certain parts of the map or townmap (the ones that are just black).

**Comment by TheMadSword** [comment]
That's very possible (regarding resting on the map). I've never crashed after this fix while initiating a random encounter; thanks (I'd believe it was my main major crash when playing this game).

**Comment by DudeMcDude** [comment]
Yeah, the cause of the crash was the "encampment" script setup. That's why it was "seldom", because it happens about 1 out of 16 times or something like that.
