### ISSUE TITLE
Black screen when locking windows

### ISSUE THREAD

**Issue by TheMadSword** [GrognardsFromHell/TemplePlus#215]
Hi,

When attempting to lock windows (Windows key + L), I lose my graphics (black screen, I guess I lose my openGL/DX context or something upon locking or unlocking).

If it can help : If I open the game and wait to see the menu, Windows+L, unlock, I see for 1 frame what seems to be the current image.

Also, I know that some tools/games have similar problem. For instance Unity had crashes in similar scenarios.

**Comment by shartte** [comment]
Hi there,

which Version of Windows are you on and which GPU are you using?

Regards
Gimp
Am 04.04.2016 5:31 vorm. schrieb "Dude McDude" <notifications@github.com>:

**Comment by DudeMcDude** [comment]
I'm getting it too actually, win7 geforce 540M here. I remember you did a device loss handling, I guess it doesn't reset correctly?

**Comment by TheMadSword** [comment]
My bad... Win7 & AMD Radeon R9 200 Series
