### ISSUE TITLE
Corrupted (but loadable) save game

### ISSUE THREAD

**Issue by TheMadSword** [GrognardsFromHell/TemplePlus#216]
Hi,

I just finished a fight against 7 trolls. I wanted to avoid the hydra-raise-and-whip-the-whole-party bug, so I decided to immediately save. This froze the game (the save box wouldn't disappear, I had to kill the game).

Since I'm dumb enough I decided to re-open the game to test the save game, before even saving the log file, so the attached log is what happens when trying to load the save game.

When loading the save game, the freeze continues.

I believe that something close to the hydra bug might be happening, as for over 10 seconds the trolls are thinking. The hydra bug didn't freeze the game though... :/

[TemplePlus.log.Corruptedsave.txt](https://github.com/GrognardsFromHell/TemplePlus/files/201643/TemplePlus.log.Corruptedsave.txt)

Github tells we can upload .zip, but it seems we can't ("Unfortunately, we don't support that file type, evne though I tried to .zip via 7z & winrar). GGWP github. ; http://www.filedropper.com/save7trollscorruptedbutloadablesave

**Comment by DudeMcDude** [comment]
Thanks, it looks like a bug with the initiative queue when a character is unconscious. It should be enough to fix the first bug / hydra bug :)
