### ISSUE TITLE
Bugbears teleporting?

### ISSUE THREAD

**Issue by pelador** [GrognardsFromHell/TemplePlus#221]
I was just fighting a room full of bugbears on the second floor of the temple and about four or five of them managed to seemingly teleport behind my party. One even visibly transported himself to the other side of the room. I don't have the logs since for some reason they haven't been recorded since the first of April, but I will have a video recording of it uploaded onto Youtube later.

**Comment by DudeMcDude** [comment]
That's a piece of scripting meant to simulate the bugbears going around the other side to flank you (it triggers when you hold a chokepoint at the entrance). Not a bug :)
