### ISSUE TITLE
Save game small image not updated in-time

### ISSUE THREAD

**Issue by TheMadSword** [GrognardsFromHell/TemplePlus#228]
Hi,

As you may or not have realized, sometimes when saving the small image representing what was in your screen at the moment of saving isn't always up-to-date.

**Comment by DudeMcDude** [comment]
Yeah I've noticed
Can you help narrow down the circumstances in which it happens?

**Comment by DudeMcDude** [comment]
Ok so it looks like this happens when you overwrite a previous save. The larger thumbnail (when you click on the save) is correct, but the smaller one in the last isn't.
