### ISSUE TITLE
[Feature] Allow +5 natural bonus on weapon / armors

### ISSUE THREAD

**Issue by TheMadSword** [GrognardsFromHell/TemplePlus#229]
Hi,

As D&D 3.5 allow +5 natural bonus, I believe allowing +5 maximum natural weapon bonus would be nice (and of course at some points enemies could possibly have them for X reason).

I understand though that it could unbalance stuff a bit; but allowing Level 11+ in a better way already kind-of unbalance it (if you compare to vanilla); but then new content can overcome this =P

**Comment by DudeMcDude** [comment]
It's impossible to imbalance a game that has Fragarach in it with that ;)

**Comment by DudeMcDude** [comment]
Done in the latest round of Item Creation overhaul. At least for weapons, I forgot about Armors/Shields, bah...

BTW the default level cap is 10, users have to manually change it to get these bonuses.
