### ISSUE TITLE
[Feature] Allow XP overflow

### ISSUE THREAD

**Issue by TheMadSword** [GrognardsFromHell/TemplePlus#232]
Hi,

as you may or may not know, when you get a level, you can keep gathering XP without taking/using that level. However, this is limited to a single level. For instance, I had a sorcerer level 10 with 65999 (66k is required for level 12) xp and he gained XP, without reaching enough xp for level 12 (I wanted to take 2 level in a row). I also don't think there is any D&D rule against that.

Imagine if you get level 20 and can't progress to 21; should one have an XP cap ? Logically a player could still gather XP.

This is already the behaviour when using cheats (to some extent, for instance, if you set your XP to 500k, you'll be able to "take" 2 level at once), so I don't think it should be too hard to code.

**Comment by DudeMcDude** [comment]
Done in 1.0.11
