### ISSUE TITLE
[Feature/Bug?] Save unlocked map elements

### ISSUE THREAD

**Issue by TheMadSword** [GrognardsFromHell/TemplePlus#236]
Hi,

As you may or not have noticed, when unlocking something, zoning out then back in and going back to the unlocked door/chest, it will be locked again. Unlocked stuff remaining unlocked would be nice (would prevent for instance interrupted pathing due to a locked door).

It would make more sense as TOEE is a very static game. Maybe let it relock if an enemy is close by (which would rarely happen though; just an idea).

**Comment by DudeMcDude** [comment]
Added option to prevent door relocking in 1.0.40
