### ISSUE TITLE
Console width when game is letterboxed

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#256]
![image](https://cloud.githubusercontent.com/assets/11220053/23862904/f185c89a-0816-11e7-93bc-6b132d99f3c7.png)

**Comment by shartte** [comment]
What's the actual bug here?

**Comment by DudeMcDude** [comment]
The console stretches beyond the cursor-lock area

**Comment by shartte** [comment]
Oh god I totally forgot about the cursor lock :D

I never start without a debugger, that's because I never notice. Yeah okay, I see the problem.
