### ISSUE TITLE
d3d error when initializing game, related to fonts

### ISSUE THREAD

**Issue by lucianposton** [GrognardsFromHell/TemplePlus#288]
Continuing from #283 : 

On version 64, when the game loads it encounters an error when trying to get text layout metrics,

```
[2018-05-03 13:28:18.127] [core] [info] Reloading font collection...
[2018-05-03 13:28:18.127] [core] [info]  Loaded Font Family: Junicode
[2018-05-03 13:28:18.128] [core] [info]  Loaded Font Family: Scurlock
[2018-05-03 13:28:18.148] [core] [warning] Direct3D Error 0x-7fffbffb @ textLayout->GetMetrics(&dWriteMetrics): 
```

I see a new font family, "Priority-12", was added recently, https://github.com/GrognardsFromHell/TemplePlus/blob/master/tpdata/templeplus/text_styles.json#L41 , but I don't see that font in https://github.com/GrognardsFromHell/TemplePlus/tree/master/tpdata/fonts . Is it missing?

In #283, @shartte said:

>I do have the following folder in my Co8 installation dir:
> `art\interface\FONTS\PRIORY\priory-12`

I don't have a FONTS dir under data/art/interface.

**Comment by shartte** [comment]
I believe you are on Wine, yes? If so, which version?
Have you tried turning up WINEDEBUG and seeing what it spews out?

**Comment by lucianposton** [comment]
3.7-staging, which now contains all my patches to fix various issues with temple+: missing d2d apis, font fallback logic (temple+'s use of arial was failing because wine vanilla doesn't fallback to checking the system font collection in the way temple+ expects), and a few stubbed apis I've think I've discussed earlier in other github issues here: https://bugs.winehq.org/show_bug.cgi?id=44052 . I only came across this issue because I fired up temple+ to test those patches since they were recently merged to 3.7-staging. The old version I had installed (56, iirc) worked fine, but after auto-updating to 64, I got this error with priory-12.

The debug output essentially indicates it is failing to calculate the text layout metrics because it is unable to find anything matching the requested font family, priory-12, in the font collection object provided by temple+ (nor in the system collection).

Can you post the priory-12 fonts? I can try dropping them in to quickly test that.

**Comment by shartte** [comment]
It shouldn't use DirectWrite for Priory12 since it's an old-style bitmap font in the DAT files.
So I wonder what code path it's taking to get there. Is this causing a crash for you? Or is it just a warning and it continues using the bitmap font afterwards?
Also: Do you have a stack trace for where the warning occurs?

**Comment by lucianposton** [comment]
It crashes during initialization at one of these two GetMetrics calls that are wrapped in D3DVERIFY, https://github.com/GrognardsFromHell/TemplePlus/blob/master/Infrastructure/src/graphics/textengine.cpp#L394 or https://github.com/GrognardsFromHell/TemplePlus/blob/master/Infrastructure/src/graphics/textengine.cpp#L410 . GetMetrics returns an error code, so the D3DVERIFY aborts the program.

I don't have a stack trace, but just eyeballing it, it looks like it occurs during font initialization in LoadFontCollection() when the loop gets to priory-12, https://github.com/GrognardsFromHell/TemplePlus/blob/master/Infrastructure/src/graphics/textengine.cpp#L817

**Comment by lucianposton** [comment]
I just looked at this again. The assumption I made in the 2nd paragraph above seems incorrect. It isn't crashing during LoadFontCollection(). It is crashing shortly after.

LoadFontCollection() appears to return successfully, as I see the subsequent calls after LoadFontCollection() in the wine debug output, https://github.com/GrognardsFromHell/TemplePlus/blob/master/Infrastructure/src/graphics/textengine.cpp#L505 :
`0035:trace:dwrite:dwritefactory_CreateTextFormat (0x1aeba48)->(L"Priory-12" 0x8d08d20 400 0 5 12.000000 L"" 0x34c9d4)`

This dwrite call with "Priory-12" as the familyName parameter succeeds, so a IDWriteTextLayout is returned, https://github.com/GrognardsFromHell/TemplePlus/blob/master/Infrastructure/src/graphics/textengine.cpp#L387. 

A few lines below that, it calls GetLineMetrics (not enough wine debug to see what that returns, but it attempts to find font family name "Priory-12" in the dwrite font collection, so I bet it returns an error, and Temple+ doesn't wrap it in D3DVERIFY to catch an error) and then GetMetrics, which returns an error code as it can't find font family name "Priory-12", aborting the process. 

I'll have to dig a little deeper when I have time. It'd be so much easier if I didn't need a windows environment for temple+ dev. :)

**Comment by lucianposton** [comment]
>I do have the following folder in my Co8 installation dir:
> `art\interface\FONTS\PRIORY\priory-12`

1) I installed toee, co8 and temple+ on win7, and it doesn't have the FONTS folder. Are you sure you have this folder? If so, I don't know where yours came from.

2) As best I can tell from the dwrite docs, calling IDWriteFactory.CreateTextFormat() with "Priory-12" as the familyName parameter when the provided font collection object contains no such family is a mistake. I could be wrong -- I have little familiarity with these windows apis. I wonder if the issue causing my crash is fundamentally that windows defaults to arial (or some system font) when it can't find "Priory-12", whereas wine returns an E_FAIL HRESULT. I'll have to write a win test case program to verify that though.

Thoughts?

**Comment by shartte** [comment]
I do believe it implements a fallback algorithm. But TemplePlus should also never hit this fallback behavior since we're not relying on the system font collection (except for Arial) and should not rely on the default fallback behavior.

**Comment by DudeMcDude** [comment]
The fonts folder should be inside one of the .dat files, you'll have to unpack them first. Co8 has made extensive use of priory 12 for upping the font size in various UIs from arial 10.
I guess the error is that it tries to find it from system first.

**Comment by DudeMcDude** [comment]
Ok, it looks like the (immediate) problem is in WidgetText::UpdateBounds(), where there is special handling for Scurlock but not Priory. I suppose a more thorough treatment should address all special fonts.

**Comment by shartte** [comment]
Heh, looking into it right now. I think I can check if the font collection HAS the font or not.

**Comment by shartte** [comment]
Pushed a PR that adds handling for the other predefined fontstyles, and refactors the existing code to remove some copypasta.

**Comment by shartte** [comment]
@lucianposton Closing the PR auto closed the issue, but could you please check if merging the PR fixes this crash for you?

**Comment by lucianposton** [comment]
Still crashing for similar reason. Here's a backtrace fwiw.

<details>
  <summary>backtrace</summary>
```
Backtrace:
=>0 0x01a9eb17 ThrowD3dAssertion+0x47(method="textLayout->GetMetrics(&dWriteMetrics)", result=0x80004005) [c:\users\worch\desktop\templeplus\infrastructure\d3d.cpp:30] in templeplus (0x0033a17c)
  1 0x019ba181 _assertD3dSuccess+0x30(method="textLayout->GetMetrics(&dWriteMetrics)", result=0x80004005) [c:\users\worch\desktop\templeplus\infrastructure\include\platform\d3d.h:24] in templeplus (0x0033a258)
  2 0x01a3a757 gfx::TextEngine::MeasureText+0xe6(formattedStr=0xa07bee8, metrics=0x33a5a4) [c:\users\worch\desktop\templeplus\infrastructure\src\graphics\textengine.cpp:394] in templeplus (0x0033a3bc)
  3 0x01557dad WidgetText::UpdateBounds+0x12c() [c:\users\worch\desktop\templeplus\templeplus\ui\widgets\widget_content.cpp:221] in templeplus (0x0033a5c4)
  4 0x015579b8 WidgetText::SetStyleId+0xb7(id=0x33aab0) [c:\users\worch\desktop\templeplus\templeplus\ui\widgets\widget_content.cpp:151] in templeplus (0x0033a6d8)
  5 0x016e4f1c LoadContent+0x24b(contentList=0x9e32cbc, widget=0xa07b938) [c:\users\worch\desktop\templeplus\templeplus\ui\widgets\widget_doc.cpp:32] in templeplus (0x0033ab88)
  6 0x016e6d1e LoadWidgetContainer+0x13d(jsonObj=0x33b668, context=0x33b644) [c:\users\worch\desktop\templeplus\templeplus\ui\widgets\widget_doc.cpp:129] in templeplus (0x0033ad38)
  7 0x016db73b std::_Invoker_functor::_Call<std::unique_ptr<WidgetBase,std::default_delete<WidgetBase> > (__cdecl*&)(json11::Json const &,WidgetLoadingContext &),json11::Json const &,WidgetLoadingContext &>+0x5a(_Obj=0x151de4, <_Args_0>=0x33b668, <_Args_1>=0x33b644) in templeplus (0x0033ae34)
  8 0x016e0f88 std::invoke<std::unique_ptr<WidgetBase,std::default_delete<WidgetBase> > (__cdecl*&)(json11::Json const &,WidgetLoadingContext &),json11::Json const &,WidgetLoadingContext &>+0x57(_Obj=0x151de4, <_Args_0>=0x33b668, <_Args_1>=0x33b644) in templeplus (0x0033af24)
  9 0x016db688 std::_Invoker_ret<std::unique_ptr<WidgetBase,std::default_delete<WidgetBase> >,0>::_Call<std::unique_ptr<WidgetBase,std::default_delete<WidgetBase> > (__cdecl*&)(json11::Json const &,WidgetLoadingContext &),json11::Json const &,WidgetLoadingContext &>+0x57(<_Vals_0>=0x151de4, <_Vals_1>=0x33b668, <_Vals_2>=0x33b644) [c:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\type_traits:16707566] in templeplus (0x0033b014)
  10 0x016e89b7 std::_Func_impl_no_alloc<std::unique_ptr<WidgetBase,std::default_delete<WidgetBase> > (__cdecl*)(json11::Json const &,WidgetLoadingContext &),std::unique_ptr<WidgetBase,std::default_delete<WidgetBase> >,json11::Json const &,WidgetLoadingContext &>::_Do_ca+0x56(<_Args_0>=0x33b668, <_Args_1>=0x33b644) [c:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\functional:16707566] in templeplus (0x0033b110)
  11 0x016e4189 std::_Func_class<std::unique_ptr<WidgetBase,std::default_delete<WidgetBase> >,json11::Json const &,WidgetLoadingContext &>::operator()+0x78(<_Args_0>=0x33b668, <_Args_1>=0x33b644) [c:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\functional:16707566] in templeplus (0x0033b214)
  12 0x016e73ee LoadWidgetTree+0x13d(jsonObj=0x33b668, context=0x33b644) [c:\users\worch\desktop\templeplus\templeplus\ui\widgets\widget_doc.cpp:225] in templeplus (0x0033b494)
  13 0x016e48ca WidgetDoc::Load+0x119(path=0x33b814) [c:\users\worch\desktop\templeplus\templeplus\ui\widgets\widget_doc.cpp:261] in templeplus (0x0033b6ac)
  14 0x01897a1c ViewCinematicsDialog::ViewCinematicsDialog+0x1db() [c:\users\worch\desktop\templeplus\templeplus\ui\ui_mainmenu.cpp:404] in templeplus (0x0033b980)
  15 0x01894ce2 std::make_unique<ViewCinematicsDialog,0>+0x71() [c:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\memory:2510] in templeplus (0x0033ba8c)
  16 0x018968da UiMM::UiMM+0x279(config=0x33d0cc) [c:\users\worch\desktop\templeplus\templeplus\ui\ui_mainmenu.cpp:60] in templeplus (0x0033c4f4)
  17 0x015fb0cf std::make_unique<UiMM,UiSystemConf &,0>+0x7e(<_Args_0>=0x33d0cc) [c:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\memory:2510] in templeplus (0x0033c604)
  18 0x015f3662 UiSystems::InitializeSystem<UiMM,UiSystemConf &>+0x91(<args_0>=0x33d0cc) [c:\users\worch\desktop\templeplus\templeplus\ui\ui_systems.cpp:159] in templeplus (0x0033cd14)
  19 0x016002cd UiSystems::UiSystems+0x38c(width=0x780, height=0x438) [c:\users\worch\desktop\templeplus\templeplus\ui\ui_systems.cpp:20] in templeplus (0x0033d100)
  20 0x01841195 TempleMain+0x264(hInstance=0x400000, commandLine=0x33e9b0) [c:\users\worch\desktop\templeplus\templeplus\temple_main.cpp:156] in templeplus (0x0033e984)
  21 0x0174d33c WinMain+0x25b(hInstance=0x400000, hPrevInstance=(nil), lpCmdLine="", showCmd=0xa) [c:\users\worch\desktop\templeplus\templeplus\main.cpp:72] in templeplus (0x0033fe30)
  22 0x01e5558e invoke_main+0x1d() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:102] in templeplus (0x0033fe48)
  23 0x01e55421 __scrt_common_main_seh+0x150() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283] in templeplus (0x0033fea0)
  24 0x01e552bd __scrt_common_main+0xc() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:325] in templeplus (0x0033fea8)
  25 0x01e55608 WinMainCRTStartup+0x7() [f:\dd\vctools\crt\vcstartup\src\startup\exe_winmain.cpp:16] in templeplus (0x0033feb0)
  26 0x7b460055 call_process_entry+0x18() in kernel32 (0x0033fed8)
  27 0x7b464035 start_process+0x1f4() in kernel32 (0x0033ffd8)
  28 0x7b460066 start_process_wrapper+0x9() in kernel32 (0x0033ffec)
```
</details>

**Comment by lucianposton** [comment]
This appears to fix the priory-12 issue.

It uncovered another issue though, but this one is solely wine's fault. Thanks

**Comment by lucianposton** [comment]
if anyone else encounters this issue, wine patches at https://github.com/lucianposton/wine/pull/4 fix the font crash issue
