### ISSUE TITLE
Critical debug failure during map load

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#302]
![2018-06-26_failure](https://user-images.githubusercontent.com/40269424/41927423-e3e6cea6-797a-11e8-875a-97e2d7d98e03.png)

(0. optional. Under debug from VS17C)
1. New game, pick any;
2. Begin Adventure.
3. Fail

**Comment by shartte** [comment]
Can you check which version of the code you are running? The line numbers in your stack trace are off from my version for some reason.
This might sound weird: But the place where it is crashing points towards corrupted game files :(

**Comment by anatoliy-savchak** [comment]
I've pulled the newest one today, and updated VS17C a moment ago. Deps are v1.14 also latest.

Does game folder requires modification too?

**Comment by anatoliy-savchak** [comment]
Also, I got half-year old sources from here (VS2015) and it loads map perfectly fine.

**Comment by shartte** [comment]
Okay, I'll have to take a closer look then. 
Can you please double-click on the first "ClippingSystem" line int he "Call Stack" view and see where exactly it's crashing?

**Comment by anatoliy-savchak** [comment]
![image](https://user-images.githubusercontent.com/40269424/41931238-2d0e7c90-7986-11e8-9aff-d53f09b64374.png)

**Comment by anatoliy-savchak** [comment]
This is my mistake. Sorry for the trouble!
