### ISSUE TITLE
itemcreation_ui_init gets altered when image is rebased

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#31]
Something alters the code, resulting in garbage code / error.
This happens in "vanilla" too (Moebius patch).

**Comment by shartte** [comment]
Hey shai, is this still current? Or is this fixed by replacing the Moebius stuff we already replaced?

**Comment by Shais2304** [comment]
Nope

I've also found this in the Moebius DLL notes:

"If you're feeling really adventurous, you can go back and figure out what sorts of relocs
you need, and edit the .reloc segment in temple.dll.  I've done this, but I'm not sure if
my edits are correct, as temple.dll is always loaded at it's preferred base, and no
relocations are necessary."

Maybe he just made an error there...

**Comment by DudeMcDude** [comment]
Replaced the itemcreation init
