### ISSUE TITLE
Targeting boxes are very tall

### ISSUE THREAD

**Issue by Dan-True** [GrognardsFromHell/TemplePlus#311]
When my party are in close quarters, I sometimes find it hard to move them about since my mouse click would rather select another party member than activate a move to a new position. E.g. in front of the top door at the ground level of the mouthouse. It was very hard placing party members, as many would be south of where I was trying to move them to.

It seems to differ slightly from character to character? E.g. my current sorceress seems to have a very large (i.e. "tall" in isometric view) selection box. Maybe it's just coincidence from other factors.

I'm not familiar with the temple plus codebase, so haven't had a look if I can fix it myself. If someone can point me to where to look I may take a crack at seeing if there is a bug at all or any possible fix.

**Comment by DudeMcDude** [comment]
I think it's based on a cylindrical hitbox. You can turn on display of the cylinders through the console rendering debug menu. (drawObjCylinders)
IIRC the cursor acquires targets via the raycast function, which is a huge and messy affair. It probably uses the cylinders though.

**Comment by shartte** [comment]
Yeah the target selection is weeeeeeeird. 
There are essentially three different ways of "hittesting" objects in ToEE:

1. By Circle, which uses the "radius" property of the object and corresponds to the selection circle you can see below the characters feet.
2. By Cylinder, which uses the "radius" and "renderHeight" properties to hit-test against a cylinder around the object.
3. By actual hit-test against the 3D model.

I actually recently fixed a bug that caused us to hit-test below the actual position of the mouse cursor. It was unclear to me whether we inherited this bug from ToEE proper, or whether we introduced it in the first place though.

If you want to look at the actual code for this, check `TemplePlus\raycast.cpp`, and especially the "PickObjectOnScreen" function in there.
You'll see that callers of that function can specify which type of hit-testing they'd like to use using the flags (GRF_HITTEST_*).

**Comment by Dan-True** [comment]
I found it was only for one of my characters - all the others have perfectly fine targeting cylidners. For some reason hers is slightly taller than the screen.

**Comment by DudeMcDude** [comment]
Than the screen? As in the entire viewport?
What race is she? And what's her height?

**Comment by Dan-True** [comment]
Yes. If she is at the bottom of my screen (i.e. just "above" their portraits) and I hover over her, I can just see the bottom of her overview card at the top of the screen.

She's a human sorceress, with the standard height (don't remember the height, but I remember not adjusting height for any characters in my party). No other party members (human or otherwise) have thir behaviour.

It's curious how much varies from character to character. The auto-equip sets work fine for my elven ranger, but not at all for my hafling rogue :S 

- Dan

**Comment by DudeMcDude** [comment]
Ah, i think that's a bug that updates the render height with wrong values. I've seen it reported before but it was hard to debug,  maybe @shartte will have more luck with the latest anim system overhaul.

**Comment by shartte** [comment]
@Dan-True Can you try enabling the debug-view shown above and post a screenshot of your affected character's cylinder?

**Comment by Dan-True** [comment]
Hm, my debug menu looks completely different. Pressing F10 give sme this:
![image](https://user-images.githubusercontent.com/16473794/47281847-3b0d0d80-d5dd-11e8-94da-6ee3436c0369.png)
![toee debug](https://user-images.githubusercontent.com/16473794/47281876-4f510a80-d5dd-11e8-9a00-431acc6f5fe2.png)
