### ISSUE TITLE
Divine Shield charisma mod bug

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#315]
Submitted via mail, reproduced here:

I noticed a minor issue which I'm not sure how to fix (or if fixable at all)
Not sure if this is a Temple+ issue, it's about the feat Divine Shield and stat mods

I think the calculation of the shield bonus is incorrect, and possibly also affected by another issue regarding stat mods.

This is the py code in the current script:
...
#Find the shield bonus
bonusValue = attachee.d20_query_with_object(Q_Armor_Get_AC_Bonus, item)
	
#Add the charisma modifier to the shield's bonus
charismaBonus = attachee.stat_level_get(stat_cha_mod)

bonusValue = bonusValue + charismaBonus

#Add the new bonus as a shield bonus.  Since shield bonuses don't stack this new bonus will
#take the place of the bonus for the shield currently used
evt_obj.bonus_list.add(bonusValue, 29, "Divine Shield Feat")
...

I think the problem here is that the Q_Armor_Get_AC_Bonus returns the AC value including the shield's enchantment bonus. The Divine Shield feat then overrides the shields AC, but not the enchantment bonus, which then get applied twice.

Furthermore, I think there is an issue with getting the correct stat_mod values in general from script - the charisma bonus being returned appears not to be the correct modified value, but instead the base mod value before any racial bonuses or spells (like +2 for drow, +4 Eagle's Splendor etc). 

It can be a bit hard to notice, since the 2 'errors' can cancel each other out so to speak (enchantment bonus applied twice + too low charisma bonus)

ex. 1: 
18 (+4) charisma, 18 dex Drow elf with a +3 shield:

normal AC: 14 +2 (shield) +3 (shield enchantment) = 19
expected Divine Shield AC: 14 +6 (divine shield: +2 shield +4 cha) +3 (shield enchantment) = 23
actual AC: 14 +8 (divine shield: +5 shield +3 cha) +3 (shield enchantment) = 25 

ex. 2:
28 (+9) charisma, 18 dex Drow elf with a +3 shield:

expected Divine Shield AC: 14 +11 (divine shield: +2 shield +9 cha) +3 (shield enchantment) = 28
actual AC: 14 +8 (divine shield: +5 shield +3 cha) +3 (shield enchantment) = 25 

so, in general the AC is too high with enchantments, but if charisma is buffed, it can be too low - the charisma mechanic is 'lost'. 
Not really sure how to fix it, since I have not found a way to get the actual correct mod values from a character, or the base shield AC without enchantment. 

Using console with a 18 charisma Drow + Eagle's Splendor:

.stat_base_get(stat_charisma) 	- returns 16
.stat_level_get(stat_charisma) 	- returns 22 (+2 drow, +4 Eagle's Splendor)

.stat_base_get(stat_cha_mod)  	- returns 3
.stat_level_get(stat_cha_mod) 	- returns 3 (should be 6?)

It's not a big issue, but was worried that the base functions might be incorrect. It's the same for all stat_mods and all races it seems, and perhaps other scripts might be affected if similar code is used for stat mods.
I could not find anyplace else in the original spell scripts where they use stat_level_get(stat_x_mod) to get the actual mod values, they mostly seem to apply a condition effect.

**Comment by DudeMcDude** [comment]
Why do you need all that hoopla? What's wrong with just adding a flat bonus that always stacks?

**Comment by doug1234** [comment]
Good point.  I was trying to make it work just like the feat but what you are saying should be the same.  I'll give it a try.

**Comment by doug1234** [comment]
Should be fixed by my pull request.  Tested with eagle's splendor and a magic shield and the AC was correct.
