### ISSUE TITLE
Game freezes PC which then reboots

### ISSUE THREAD

**Issue by valepu** [GrognardsFromHell/TemplePlus#330]
Hello,
I'm having a issue with the game. When I started it up the first time everything went fine. I opened and closed it several times while creating my characters (took my time between creating one character and the other), then I played a bit, saved the game and closed it.
The day after i opened the game and the menu was extremely slow, then after a few seconds my PC froze (i was running in a window so i could notice i couldn't click on anything else). I waited like 30 seconds and it rebooted (and I have this feeling it rebooted because my graphic card was overheating).
Other attempts went similarly, except i managed to be fast enough to quit the game before my PC completely froze.

When I run ToEE using Co8 or just the normal game this doesn't happen

**Comment by DudeMcDude** [comment]
What are your system specs? (Hardware, OS) What resolution and Temple+ config options are you using?

**Comment by valepu** [comment]
Hi, thanks for your answer. These are my specs:

OS: Windows 10
GPU: Geforce GTX 780M
CPU: Intel i7-4700HQ 2.4Ghz
RAM: 24 GB (Kingston)

This is the TemplePlus.ini file
```

[TemplePlus]
NPCsLevelLikePCs=true
additionalTioPaths=
alertAiThroughDoors=false
allowXpOverflow=true
antialiasing=false
autoUpdate=true
d3dDebug=false
debugMessageEnable=true
debugPartSys=false
defaultModule=ToEE
disableAlignmentRestrictions=false
disableCraftingSpellReqs=true
disableDoorRelocking=false
disableMulticlassXpPenalty=true
displayAdapter=0
dungeonMaster=true
fastSneakAnim=false
featPrereqWarnings=false
fogOfWar=normal
forgottenRealmsRaces=true
hpOnLevelup=normal
laxRules=true
lockCursor=true
maxHpForNpcHitdice=false
maxLevel=20
maxPCs=5
maxPCsFlexible=true
monstrousRaces=true
msaaQuality=0
msaaSamples=4
newAnimSystem=false
newClasses=true
newFeatureTestMode=true
newRaces=true
noSound=false
nonCoreMaterials=true
pathfindingDebugMode=false
pointBuyPoints=50
renderHeight=800
renderWidth=1280
screenshotQuality=80
sectorCacheSize=128
showExactHPforNPCs=true
showNpcStats=true
showTargetingCirclesInFogOfWar=false
skipIntro=true
skipLegal=true
slowerLevelling=false
softShadows=false
speedupFactor=1.000000
spellAlreadyKnownWarnings=false
toeeDir=C:\Program Files (x86)\GOG Galaxy\Games\Temple of Elemental Evil
tolerantNpcs=true
upscaleLinearFiltering=true
walkDistanceFt=0
windowHeight=800
windowWidth=1280
windowed=true
windowedLockCursor=false
[Vanilla]
3d volume=2
always run=1
astar_max_time_ms=4000
astar_max_window_ms=5000
auto attack=1
autosave_between_maps=1
brightness=0
cloth_frame_skip=0
combat taunts=1
concurrent_turnbased=1
difficulty=1
draw_hp=0
effects volume=2
end_turn_default=1
end_turn_time=1
env_mapping=1
fast turn-based=0
float_speed=1
fog checks=1
follower skills=1
hide_invalid=1
hide_pregen=1
movies_seen=(304,-1)(300,-1)
music volume=0
particle_fidelity=100
partsys_fidelity=100
radialmenu_click_to_activate=0
scroll_butter=300
scroll_butter_type=1
scroll_speed=1
shadow_type=2
shadows=0
startup_tip=-1
text duration=6
text_floaters=2147483647
turn-based=1
video_adapter=0
video_antialiasing=0
video_bpp=32
video_height=600
video_quad_blending=1
video_refresh_rate=60
video_width=800
violence filter=0
voice volume=2

```

I'm also attaching TemplePlus.log, thought it might be useful
[TemplePlus.log](https://github.com/GrognardsFromHell/TemplePlus/files/2953970/TemplePlus.log)

Let me know if you need anything else

**Comment by valepu** [comment]
Could be related to this? https://github.com/GrognardsFromHell/TemplePlus/issues/220
I did not get a precise measurement because my PC rebooted but it felt pretty hot on touch (in my case it was on the start menu though)

**Comment by valepu** [comment]
Any news on this? I have tried uninstalling everything and reinstalling it without circle of eight modpack but it still doesn't work

**Comment by DudeMcDude** [comment]
Sorry, no idea.

**Comment by shartte** [comment]
Yes, sorry @valepu, but without being able to reproduce this, it's likely impossible to find the issue and fix it.
In most cases, freezes like that relate to the graphics driver.
The only other thing I can think of is looking into the Windows Event Viewer to try and figure out *why* it restarted.

**Comment by valepu** [comment]
Thanks, 
I'm sorry for asking if there were any news but It felt bad being locked out of the game. I was actually trying to implement the divine metamagic feat when this happened so not being able to progress on that was a bit frustrating.
I know and understand this is a open source fan project and by no means i meant to put pressure. I'll try to figure it out by myself and post any progress should i find a solution

**Comment by valepu** [comment]
Apparently it actually was a graphic drivers issue. I have recently tried playing again the game and it's working without issues. There's been a few updates on my graphic drivers in the last days so it must've been it

**Comment by DudeMcDude** [comment]
Glad to hear!
