### ISSUE TITLE
Sudden widen causes spells slots not to expend

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#352]
Reported by user on rpgcodex

**Comment by doug1234** [comment]
Just tested and it worked fine with a level 3 sorcerer.  Which class and what spell caused the problem?

**Comment by DudeMcDude** [comment]
They didn't say, but I'd guess Wizard since they mentioned slots. Just tested it myself, can confirm that any spell with any sudden X applied does that (and the Sudden works more than once too).

**Comment by doug1234** [comment]
I am seeing the same thing with a wizard.  Looks like I have been testing with spontaneous casters too much.  Fix hopefully coming tonight or early next week.

**Comment by doug1234** [comment]
The vancian part of the Debit() logic is getting confused by the updated meta magic info.  I have a fix but I need to test it a bit more next week.

**Comment by DudeMcDude** [comment]
No pressure, take your time.

**Comment by doug1234** [comment]
Since you merged it in I assume its good to go.
