### ISSUE TITLE
Text description overflow

### ISSUE THREAD

**Issue by Psionics-ToEE** [GrognardsFromHell/TemplePlus#355]
When looking at feats to level up, the description on them overflows the box instead of fitting inside and using the scrollbar. This issue may be present with descriptions of all sorts, not just feats. Not sure how this could be fixed in this case though because when you mouse off of the feat in levelup the description goes away, so there's no way to keep it there so you could move your mouse down to scroll within the description box.

![description overflow](https://user-images.githubusercontent.com/22106339/62416352-c1d82780-b5fe-11e9-8396-0c22d4236325.png)

**Comment by DudeMcDude** [comment]
I think it shouldn't scroll. These descriptions should be short and to the point. Keep the encyclopedic entries for the full help entries.
