### ISSUE TITLE
Levelup console command and gui cheat option doesn't work past level 10

### ISSUE THREAD

**Issue by Psionics-ToEE** [GrognardsFromHell/TemplePlus#358]
As the title says. Once I hit level 10 with 45000 XP, I can use levelup or press the level up button through console UI but I do not gain any more levels. I do get the correct XP gain, once from 45000 to 55000. Stepped through debugging tig_console.cpp and everything checked out in the levelup section.. the character simply doesn't gain a level after gaining the experience. The XP table calculation is 55000 for level 11 based on the c++ code, so I'm not sure at the moment where the problem lies.

**Comment by DudeMcDude** [comment]
You need to config max level
