### ISSUE TITLE
Hangs in the tray and the game does not start

### ISSUE THREAD

**Issue by appath** [GrognardsFromHell/TemplePlus#370]
Hangs in the tray, but the game does not start
Yesterday everything worked, but today, alas.
Yes, such a question where leaves the keys in the registry path TemplePlus

![Безымянный](https://user-images.githubusercontent.com/13101595/71744067-3990d380-2e77-11ea-873d-dd6807e1dc1e.png)

**Comment by shartte** [comment]
Hmmm that is weird, we have been getting reports of this happening since 2020 essentially, but no updates were pushed by us :-|

**Comment by appath** [comment]
In general, here is the file, pulled it out. If it’s not difficult, take a look.
[https://drive.google.com/open?id=1MOMG2MH4jCGwq8f-7tM8koxDhIqyvGmU](url)

**Comment by appath** [comment]
Generally pulled out a dmp file, if not hard to help than you can solve the problem.
* [DMP-file](https://drive.google.com/open?id=1MOMG2MH4jCGwq8f-7tM8koxDhIqyvGmU)

**Comment by appath** [comment]
Is there a way out or is there horror?

**Comment by shartte** [comment]
@appath Thank you for submitting the dmp file. It is hanging on loading the TemplePlus.ini file! I have actually observed such a thing myself. Could you please delete your TemplePlus.ini file and try again?
(It is located in C:\Users\<...>\Saved Games\TempePlus)

**Comment by doug1234** [comment]
Might be nice to have a copy of the ini file if it turns out to be causing the issue.

**Comment by appath** [comment]
Thanks for the help, it’s strange and real (the file was deleted TemplePlus.ini) and after that everything worked like the first time.

I have a question for the guys, TemplePlus will leave the keys in the registry?

**Comment by shartte** [comment]
@appath Marking this issue as closed then.

I do not understand your last question though. We don't use the registry for saving settings.

**Comment by appath** [comment]
Is it possible to change the path?
C:\Users\Boris\Saved Games\TemplePlus
So that folder (TemplePlus) is where I need it

**Comment by shartte** [comment]
You can change the location of your Saved Game folder in Windows, and TemplePlus will use that new 
location.
This works the same way as changing the location of your documents folder for example. (Try right clicking the "Saved Games" folder and going to Properties. There's a "Location" tab there that allows it's location to be changed):

![grafik](https://user-images.githubusercontent.com/1261399/71781497-e3837380-2fcf-11ea-8b5b-5ffc2febee70.png)

**Comment by appath** [comment]
Thank you friend, but I know that. 
Probably have to decide even. In general, I am building a Portable game and I want to include your Temple+ in a portable (Not how I can not get the portable to take the tail **C:\Users\Boris\Saved Games\TemplePlus\*)** so that the portable picks up the temporary folder **Data\TemplePlus\*** at closing portable.

**Comment by shartte** [comment]
Sorry, that is currently not supported.

Boris <notifications@github.com> schrieb am So., 5. Jan. 2020, 15:56:
