### ISSUE TITLE
Compiling on Linux?

### ISSUE THREAD

**Issue by brzegorz** [GrognardsFromHell/TemplePlus#373]
Hi, would it be possible to compile and run TemplePlus on Linux? I've made initial attempts trying to use various tools for .sln files(msbuild, some converters to makefile/cmake etc.), but without success.

If I were to write a cmake/makefile, would it be technically possible to compile on linux, or are there some windows-exclusive dependencies, e.g. DirectX?

**Comment by shartte** [comment]
Sadly, this is currently not possible, and likely never will be for TemplePlus.

TemplePlus itself has some native Windows dependencies (Direct3D11, Direct 2D, Window and Input Management).

But even if we somehow managed to use platform-independent libraries instead, TemplePlus still loads the original ToEE's temple.dll, which itself is a Windows-only library and has more Windows-only dependencies.

A project's in the works that'll solve the reliance on ToEE's temple.dll, but it's still some ways off.
