### ISSUE TITLE
Update to VS 2019

### ISSUE THREAD

**Issue by shartte** [GrognardsFromHell/TemplePlus#378]
@doug1234 As one of the major contributors, is there anything that would block you from using VS2019 community?
@DudeMcDude Any blocker on your end?

If not, I'll update the precompiled dependencies to VS2019 and update the solution files.

**Comment by doug1234** [comment]
I have VS 2019 installed already.  I was actually planning to ask you if I could update Temple+ to it when I had some time.  So I think updating is a great idea!

BTW:  Any chance you can update the .NET framework version while you are at it?

**Comment by shartte** [comment]
Oh, sure, I should be able to do that. But will focus on VS 2019 first.

**Comment by DudeMcDude** [comment]
Newer is always better!

**Comment by shartte** [comment]
@DudeMcDude @doug1234 I did get it working on VS2019 in  #379
Appveyor is also still building (I could not re-run the branch build because it's in dude's account) successfully.
You'll need to download the v1.6 dependencies from here:
https://github.com/GrognardsFromHell/Dependencies/releases

**Comment by doug1234** [comment]
Downloaded the dependencies and I built and tested your changes.  They look good to me.

**Comment by shartte** [comment]
Fixed by #379
