### ISSUE TITLE
Wood Elves don't have Charisma penalty

### ISSUE THREAD

**Issue by Hettikus** [GrognardsFromHell/TemplePlus#390]
They only gein -2 to int and -2 to con, but not to cha.

**Comment by valepu** [comment]
That might actually be correct. It depends if we are using FR wood elves or Monster Manual wood elves

Monster Manual Wood Elves have +2 str, +2 des, -2 int, -2 con
https://www.d20srd.org/srd/monsters/elf.htm#wildElf (notice it says the stats changes are in addition to those of a standard elf)

Forgotten Realms Wood Elves also have a -2 to Charisma

**Comment by Hettikus** [comment]
I compare it to the help entry in the game. So either race or help topic
should be changed :)

чт, 30 апр. 2020 г. в 14:00, valepu <notifications@github.com>:

**Comment by doug1234** [comment]
Documentation updated to the in game stats which match the SRD.
