### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by sheldonooi** [GrognardsFromHell/TemplePlus#401]
Hi. I've been trying to compile TemplePlus from scratch, but I seem to be running into the error below:

13>C:\Users\Sheldon Ooi\Desktop\TemplePlus-master\TemplePlus\common.h(219,19): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'const char [2]' (or there is no acceptable conversion) (compiling source file portrait_in_mainmenu.cpp)
13>C:\Users\Sheldon Ooi\Desktop\TemplePlus-master\TemplePlus\common.h(215,22): message : could be 'std::ostream &operator <<(std::ostream &,const ScreenDirections &)' (compiling source file portrait_in_mainmenu.cpp)
13>C:\Users\Sheldon Ooi\Desktop\TemplePlus-master\TemplePlus\d20_defs.h(98,15): message : or       'std::ostream &operator <<(std::ostream &,D20ActionType)' (compiling source file portrait_in_mainmenu.cpp)

Am I doing something wrong?

Thanks.

**Comment by shartte** [comment]
You do need to provide more info, i.e. which compiler version are you using, which operating system, etc.

**Comment by sheldonooi** [comment]
I'm using Microsoft Visual Studio 2019 on Windows 8.1. I sort of worked around the issue by adding #include <iostream> which clears the error, though I'm unsure whether that actually fixes the issue, or VS2019 was just being wonky.

**Comment by shartte** [comment]
I am seeing this problem on the master branch as well when Github Actions builds it.
Must have been a VS 2019 update.

**Comment by DudeMcDude** [comment]
Should be fixed now, can you try?

**Comment by doug1234** [comment]
The nightly build for my fork is now passing (it was getting that error previously).

**Comment by sheldonooi** [comment]
Sorry, was away for some time. Just got the latest version and everything compiles. Thanks!
