### ISSUE TITLE
Constant crash at moathouse dungeon

### ISSUE THREAD

**Issue by eyn85** [GrognardsFromHell/TemplePlus#406]
Hey I sent an email at templeplushelp@gmail.com but I just found out this forum and gonna post here also, so I installed both CO8 8.1 NC and temple plus latest version(1.0.7.9 i think) and was playing with no issues until the moathouse it seems, everytime I try to fight Lareth guards I get an crash, dunno if is because of my Bard trying to use charm person since I am dying like crazy on this fight...anyway I just get an constant crash and it generates an DMP file and I followed all the instructions in the crash window and managed to get the DMP crash files and my save files... I cant seem to post it here since the forum doesnt accept it nor my save files extension...anyway I emailed there and all the files are anexed on it...thanks in advance

**Comment by DudeMcDude** [comment]
Addressed.
