### ISSUE TITLE
Crash at the broken tower fight

### ISSUE THREAD

**Issue by eyn85** [GrognardsFromHell/TemplePlus#409]
Hey there just sent my save files and the DMP file that the crash generated on templeplusgmail....this crash happened once at the fight against the bandits in the broken tower...I think it was something that the enemy witch did(or my bard song again I dunno) anyway just wanted to report here

**Comment by uralets** [comment]
Had repeated crashes there too. Taught me to quicksave during the fight.

**Comment by DudeMcDude** [comment]
Hmm, I was never able to replicate that crash... do you have a save that reliably demonstrates a crash there?

**Comment by uralets** [comment]
В Вс, 31/01/2021 в 08:27 -0800, Dude McDude пишет:
> Hmm, I was never able to replicate that crash... do you have a save
> that reliably demonstrates a crash there?

No I'm afraid not, I'm past that point. But it was quite reliable, it
crashed 2 or 3 times in a row during that battle.
I should have the dumps though, however I won't be able to send you
only the ones created after those crashes, bc there's a few of them
piled up. The game crashes from time to time.

**Comment by DudeMcDude** [comment]
Recently fixed several issues affecting that fight, maybe they were the same... in particular an issue in Ready Vs. Spell (that the crossbowmen) use which could cause a crash when Produce Flame was used.
Closing this issue, feel free to reopen if you have new information.

**Comment by DudeMcDude** [comment]
> В Вс, 31/01/2021 в 08:27 -0800, Dude McDude пишет:
> Hmm, I was never able to replicate that crash... do you have a save that reliably demonstrates a crash there?
> No I'm afraid not, I'm past that point. But it was quite reliable, it crashed 2 or 3 times in a row during that battle. I should have the dumps though, however I won't be able to send you only the ones created after those crashes, bc there's a few of them piled up. The game crashes from time to time.

Oh, I missed that you do have the crash dumps. Please do send them if you still have them (all of them, doesn't hurt).
