### ISSUE TITLE
UI resize flicker

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#42]
When using a window that is the size of my full screen resolution, you get a strange flicker when changing maps

**Comment by Shais2304** [comment]
This happens in fullscreen mode too (use d3dex = true)

**Comment by shartte** [comment]
This is a pretty old bug. Is this still relevant after the render changes?

**Comment by DudeMcDude** [comment]
Yes, though to a somewhat lesser extent.

The issue is that on map change, the scene gets stretched / distorted when render != window size.

**Comment by DudeMcDude** [comment]
Solved by gfade implementation :)
