### ISSUE TITLE
Favored Soul

### ISSUE THREAD

**Issue by Jaysyn904** [GrognardsFromHell/TemplePlus#420]
My Favored Soul of Pelor didn't get any Domain powers.

[Gleem.zip](https://github.com/GrognardsFromHell/TemplePlus/files/5247108/Gleem.zip)

**Comment by doug1234** [comment]
My understanding is that they should not get domain powers.

**Comment by Jaysyn904** [comment]
You're absolutely right.  I was confused because he still got the Domain Power feat.

![image](https://user-images.githubusercontent.com/68194417/93668906-e4750c00-fa5d-11ea-9750-a1e74c9ef537.png)

**Comment by doug1234** [comment]
Sounds good.  Closing out.
