### ISSUE TITLE
Warmage Spells Missing on Level up

### ISSUE THREAD

**Issue by Jaysyn904** [GrognardsFromHell/TemplePlus#423]
Bug:  My Warmage only has the option of Wind Wall for 3rd level spells.

Expected Behavior:  I was expecting the 3.5e warmage spell list or as close to it as ToEE can get.

Fire Shield, Fireball, Flame Arrow, Gust of Wind, Ice Storm, Lightning Bolt, Poison, Ring of Blades, Sleet Storm, Stinking Cloud

The 2nd level list seems a little light too.

![image](https://user-images.githubusercontent.com/68194417/93673057-2cedf300-fa79-11ea-875d-3add5f567d2a.png)

[BrokenWarmage.zip](https://github.com/GrognardsFromHell/TemplePlus/files/5250245/BrokenWarmage.zip)

**Comment by Jaysyn904** [comment]
Nevermind, I'm an idiot.

**Comment by doug1234** [comment]
You only select spells for advanced learning (extra evocations spells not normally on the warmage list).  You should automatically get the other spells after you level up.

**Comment by doug1234** [comment]
Looks like you figured it out...

**Comment by Jaysyn904** [comment]
Nevermind, I'm an idiot.
