### ISSUE TITLE
Visual Studio 16.8 dependency rebuild

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#445]
Error when building T+ with new VS 16.8 Community Edition:
'..TemplePlus\dependencies\lib\python27.lib' was created by a different version of the compiler than other objects like '..\TemplePlus\Release\\EASTL.lib'; rebuild all objects and libraries with the same compiler.

@shartte FYI

**Comment by shartte** [comment]
Please try the new build of dependencies found here: 

https://github.com/GrognardsFromHell/Dependencies/releases/tag/v1.7

(And remember to fully clean/rebuild)
