### ISSUE TITLE
Linux/Wine crashes

### ISSUE THREAD

**Issue by uralets** [GrognardsFromHell/TemplePlus#458]
Hello!
I understand that running via wine isn't supported, but maybe you could point me in the right direction.

Stuff I'm running:
the latest Wine 6.0 (32 bit prefix, tho I've tested with an amd64 one just for completionism sake)
GOG distribution
installed and activated the latest Co8
launching T+ from the unpacked .zip archive (the latest one from github).
Also I've installed dxvk without which the game would crash right away even before the splash screen.

TemplePlus.exe (and the config tool too) now launches and I can even start the tutorial, but it crashes at various points (which are always the same) seemingly unconnected to each other. The windows error msg window pops up but it isn't helpful, it's the standard "This application has requested the Runtime to terminate it in an unusual way", there's no output in the terminal after the crash (apart from fixme:ver:GetCurrentPackageId (0068FEA4 00000000): stub). The backtrace in winedbg isn't helpful either.

Some of the actions always causing the crash:
new game -> choose party alignment -> Accept -> Crash
Options -> View Cinematics -> Crash
While actually playing the tutorial, innocuous stuff like hitting rest, just hovering over the char's skills (but not over stats or spells - those work), double-clicking the wand you pick up also cause it.

Now I've tried pretty much everything I could think of including changing Wine's emulated windows versions, installing various support libs (from the winetricks menu, like vcrun2019 and stuff), changing settings in the config tool to run windowed, diff. resolutions, **nothing** seems to affect it. It always crashes at the same places.

I thought somebody here could help me with what could be the common thing between those actions? I mean hitting the rest button (the green tent) should just bring up a rather simple menu, tons of other menus and such are working fine. Hovering over the skills even more mysterious. The Cinematics menu too. What could possibly be tripping all these?

Co8 launches and works well (as far as I've checked it).

TIA

**Comment by DudeMcDude** [comment]
I'd guess it's something rendering related, perhaps to text... I did recently hook the skills display (to support additional skills).
Does it create the Temple+ logfile? Anything interesting in there?

**Comment by shartte** [comment]
> The backtrace in winedbg isn't helpful either.

What _is_ the backtrace though?

We use DirectWrite/Direct2D for rendering. However, those should actually be well imlemented in wine.

**Comment by uralets** [comment]
Strange.. I thought whenever I checked the logs they ended up empty.
Well, there's this after trying to start a new game - https://pastebin.com/Yp6rJiJw
Hovering over skills in the tutorial - https://pastebin.com/TbErBcv1
Both are just cut off halfway through the last line

winedbg backtrace https://pastebin.com/EZftzQ4e

also strace'ing wine isn't too helpful
WINEDEBUG=+relay (or +snoop) just spams the output and the game I think have never even "booted" once properly for me with those debug channels on

**Comment by shartte** [comment]
> Unhandled exception: C++ exception(object = 0x0031f26c, type = 0x00b8754c) in 32-bit code (0x7b00fd36).

This is interesting. So it's a C++ exception, huh. Weirdly the global handler doesn't seem to catch it.
Can winedbg load PDBs?

**Comment by uralets** [comment]
В Вс, 17/01/2021 в 13:31 -0800, shartte пишет:
> > Unhandled exception: C++ exception(object = 0x0031f26c, type =
> > 0x00b8754c) in 32-bit code (0x7b00fd36).
> > 
> 
> This is interesting. So it's a C++ exception, huh. Weirdly the global
> handler doesn't seem to catch it.
> 
Yeah, it's in the C++ code. Guess I should've mentioned that.

> Can winedbg load PDBs?
Debug symbols? I'm less familiar w/debugging for windoze. I'd think so.
I'll try and investigate.

**Comment by uralets** [comment]
There seems to be support for PDBs

**Comment by shartte** [comment]
The AppVeyor builds should actually also build PDBs in addition to the executable.

Can you grab the executable and PDB file from here: 
https://ci.appveyor.com/project/templeplus/templeplus/build/artifacts

The PDB is in the symbols ZIP file (in the release subfolder).

That _should_ give you a proper backtrace with names and make this a thousand times easier to figure out.

**Comment by uralets** [comment]
https://github.com/GrognardsFromHell/TemplePlus/blob/5aed7b8866703e075bf5ac773a92951f3babf64e/TemplePlus/ui/widgets/widget_content.cpp#L200
could it be called here?

**Comment by shartte** [comment]
I'd guess it is this:

https://github.com/GrognardsFromHell/TemplePlus/blob/f033cd75c6d06233e300664b424daffb27b12a3c/Infrastructure/src/graphics/textengine.cpp#L274

**Comment by uralets** [comment]
There seems to be no shortage of Wine release announcements containing references to improvements in Direct2D/DirectWrite implementation, but very little on how to investigate problems with it.
Unless file a bug with Wine itself.. Duh.

**Comment by shartte** [comment]
Filing a bug would probably only make sense if we'd actually see the error code being handled here.

**Comment by uralets** [comment]
```
Breakpoint 1 at 0x004ae51b ThrowD3dAssertion+0x2b in templeplus
Wine-dbg>print
syntax error
Wine-dbg>print result
No symbols found for result

Undefined symbol
Wine-dbg>cont
WARNING: radv is not a conformant vulkan implementation, testing use only.
00cc:fixme:dwrite:dwritefactory_CreateMonitorRenderingParams (0x1): monitor setting ignored
Thread ID=013c not in our list of threads -> can't rename
Thread ID=0140 not in our list of threads -> can't rename
0024:fixme:dbghelp:i386_stack_walk new PC=7b099b different from Eip=3b00e59
Stopped on breakpoint 1 at 0x004ae51b ThrowD3dAssertion+0x2b in templeplus
Wine-dbg>print result
0x80004005

Wine-dbg>step
<snip>
0x004ae520 ThrowD3dAssertion+0x30 in templeplus: pushl  $0x24
Wine-dbg>print result
0x3
Wine-dbg>step
<snip>
Backtrace:
=>0 0x7b00fd36 EntryPoint+0xffffffff() in kernelbase (0x0031f218)
  1 0x008954fc _CxxThrowException+0x65(pExceptionObject=0x31f26c, pThrowInfo=0xb88c3c) [d:\agent\_work\57\s\src\vctools\crt\vcruntime\src\eh\throw.cpp:74] in templeplus (0x0031f254)
  2 0x004ae55c ThrowD3dAssertion+0x6b() in templeplus (0x0031f284)
  3 0x00478f3e gfx::TextEngine::RenderText+0x25d(rect=(nil), formattedStr=(nil)) in templeplus (0x0031f2f0)
<snip>
```
Using +relay will probably need filtering some libraries out first. I've tried without and it crashes before reaching the menu.

**Comment by shartte** [comment]
`
E_FAIL | Unspecified failure | 0x80004005
-- | -- | --
`

Oh boy... :-D
Unspecified failure is not exactly helpful from Wine here.

**Comment by uralets** [comment]
Great.
What about 0x3 or 0x31f248 ?

**Comment by shartte** [comment]
No, 0x80004005 is the error code returned by GetMetrics. So that's the only usable thing here, other than the Wine Debug messages.

If you'd want to report this to wine, the report is essentially DirectWrite GetMetrics failing with E_FAIL, and the log messages.
Are you sure `WARNING: radv is not a conformant vulkan implementation, testing use only.` has nothing to do with it?

**Comment by shartte** [comment]
Oh, wait.

I actually found an old post on this very issue tracker that reports the same problem ;-)

https://github.com/GrognardsFromHell/TemplePlus/issues/288#issuecomment-388653755

We can try to work around this problem for wine.

**Comment by uralets** [comment]
В Пн, 18/01/2021 в 03:54 -0800, shartte пишет:
> No, 0x80004005 is the error code returned by GetMetrics. So that's
> the only usable thing here, other than the Wine Debug messages.
> 
> If you'd want to report this to wine, the report is essentially
> DirectWrite GetMetrics failing with E_FAIL, and the log messages.
> Are you sure WARNING: radv is not a conformant vulkan implementation,
> testing use only. has nothing to do with it?
> 
I've tried with amdvlk which is conformant supposedly (no message).
I've tried a lot of things blindly)

Anyway I believe radv has been good for some time now and the warning
is probably outdated (see eg 
https://www.phoronix.com/scan.php?page=article&item=mesa-201aco-amd&num=2
)

**Comment by uralets** [comment]
В Пн, 18/01/2021 в 03:55 -0800, shartte пишет:
> Oh, wait.
> 
> I actually found an old post on this very issue tracker that reports
> the same problem ;-)
> 
> #288 (comment)
> 
> We can try to work around this problem for wine.
> 

Umm.. I've referenced this some posts before)

**Comment by shartte** [comment]
Sorry, I totally read past that :-8

**Comment by uralets** [comment]
Wonder if it could be worked around without compiling wine from scratch! Duh. This game better be worth it.

**Comment by shartte** [comment]
No, don't go ahead and do that. I'll look into it. The font fallback is something we can work around I think.
the other question would be: Do you have Arial?

**Comment by uralets** [comment]
В Пн, 18/01/2021 в 04:18 -0800, shartte пишет:
> No, don't go ahead and do that. I'll look into it. The font fallback
> is something we can work around I think.
> the other question would be: Do you have Arial?
> 
Initially stumbling upon #288 I've installed the good old Corefonts.
Didn't seem to change anything either. I'll try and make sure it's
installed.

**Comment by shartte** [comment]
It's possible that the problem wine has is actually that it does not "properly" fall back to Arial when the font name just doesn't match. But regardless. I'll go and check our code and see if we can avoid relying on automatic fallback.

**Comment by uralets** [comment]
Would be a life saver)
I've also installed the Priory font which again didn't help.

**Comment by shartte** [comment]
@uralets Can you please check if there's a file `tpdata/fonts/mapping.json`?
If yes, please make a backup, and then replace its content with just `[]` and try if that changes anything for you.

**Comment by uralets** [comment]
В Пн, 18/01/2021 в 08:55 -0800, shartte пишет:
> @uralets Can you please check if there's a file
> tpdata/fonts/mapping.json?
> If yes, please make a backup, and then replace its content with just
> [] and try if that changes anything for you.
> 

Fuckin genius. Could even start a new game! And the skill descriptions
show up fine.
Thank you kindly for you time!

However, clicking on the Cinematics menu still causes a crash...
But this requires a little more investigating (even if it the same
issue or otherwise).

BTW, the intro won't play when I launch the game. Is it by design? The
Co8 executable plays the intro on launch.

**Comment by shartte** [comment]
So, I think I have a hunch what the problem is. Essentially it doesn't find Arial and just crashes. I'll investigate a bit further.

**Comment by uralets** [comment]
Ah, I see.

Turns out there's another crash when playing video (atari), now caused by HookedPlayMovieBink (this one gets caught properly tho). Maybe I need to install some compat stuff like codecs into wine.

But accessing the Cinematics menu is still a fonts issue, as the debugger tells me. Useful thing these debug symbols..

But that's for another day) Thank you again!

**Comment by shartte** [comment]
Can you try putting an Arial.ttf into tpdata\fonts ?
Temple+ will just auto-load all ttfs from that folder (it should at least), this might actually make Arial available, and potentially fix the cinematics dialog (and other potential problems).

**Comment by uralets** [comment]
В Пн, 18/01/2021 в 10:04 -0800, shartte пишет:
> Can you try putting an Arial.ttf into tpdata\fonts ?
> Temple+ will just auto-load all ttfs from that folder (it should at
> least), this might actually make Arial available, and potentially fix
> the cinematics dialog (and other potential problems).

You are right, putting arial.ttf into fonts/ seems to fix the font
crashes, with the mapping too. Great work!

Now I need to figure out the damned Bink issue and maybe I'd be able to
do some proper turn-based d&d dungeon crawling!
I'm not even sure I still want to)) The chase is better than the catch
and all that...)

Hope it helps to make T+ a bit more stable at least.
The fully native version (and of the game itself) would've been a
blast...

**Comment by shartte** [comment]
I'll need to push another build to fix the logfile issue, which might help with debugging why movies dont play.

**Comment by uralets** [comment]
Found out that it's only the Atari logo which causes the crash. The intro plays fine.

**Comment by tarasis** [comment]
> Can you try putting an Arial.ttf into tpdata\fonts ? Temple+ will just auto-load all ttfs from that folder (it should at least), this might actually make Arial available, and potentially fix the cinematics dialog (and other potential problems).

2 years later, and this was exactly was was causing my crash (trying to run TempletePlus.exe on Apple Silicon + WineSkin-Winery). I tried installing corefonts but it put it into a different windows fonts directory.

Copied the file in like you said, and I could move past the Alignment select screen. 

Thank you
