### ISSUE TITLE
New spells have buggy XSpellIsActive callbacks

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#470]
Example:
https://github.com/GrognardsFromHell/TemplePlus/blob/183509ba001ac320932883df702d3250b7c48df0/tpdatasrc/tpgamefiles/scr/tpModifiers/sp_moment_of_prescience.py#L108

This will return 1 regardless of the spell enum being queried. Looks like a forgotten placeholder.

**Comment by doug1234** [comment]
Good find.  I'll make sure something like this doesn't effect any other spells and should have a pull request on Monday.
