### ISSUE TITLE
Corrupted quick save

### ISSUE THREAD

**Issue by uralets** [GrognardsFromHell/TemplePlus#476]
First in about 4 runs
[qwik1.zip](https://github.com/GrognardsFromHell/TemplePlus/files/6279591/qwik1.zip)
```
Backtrace:
=>0 0x006cb841 GameObjectBody::ValidateFieldForType+0x11(field=obj_f_item_inv_location) in templeplus (0x0031f26c)
  1 0x006c92e0 GameObjectBody::GetInt32+0x6f(field=obj_f_item_inv_location) in templeplus (0x0031f2b4)
0140:fixme:winedbg:print_value ---error
  2 0x0068e6e7 D20StatusSystem::initItemConditions+0xf6(objHnd=) in templeplus (0x0031f3f4)
0140:fixme:winedbg:print_value ---error
  3 0x0068d26a D20StatusSystem::D20StatusInit+0x189(objHnd=) in templeplus (0x0031f448)
  4 0x006c449a std::_Func_impl_no_alloc<<lambda_1346e30c9f8e70a967df585100f85522>,void,objHndl,GameObjectBody &>::_Do_call+0xd9(<_Args_0>=0x31f4d4, <_Args_1>=0x9eb7de0) in templeplus (0x0031
f4b8)
0140:fixme:winedbg:print_value ---error
  5 0x006d23ca ObjSystem::ForEachObj+0x89(callback=) in templeplus (0x0031f4ec)
  6 0x006c1c8d MapSystem::OpenMap+0x3ac(mapEntry=0x9b5f4a4) in templeplus (0x0031f5cc)
  7 0x006bf8b8 MapSystem::LoadGame+0x287(saveFile=0x31f760) in templeplus (0x0031f73c)
  8 0x0080f8a7 GameSystems::LoadGame+0x4b6(filename=0x31f80c) in templeplus (0x0031f7f4)
  9 0x0080f38d GameLibLoadReplacement::LoadGame+0x6c(filename="SlotQwik") in templeplus (0x0031f834)
  10 0x1011294a EntryPoint+0xffffffff() in temple (0x0031f888)
  11 0x0084ff45 UiManager::ProcessMessage+0x124(msg=0x31f8c4) in templeplus (0x0031f8b0)
  12 0x006e6858 MessageQueue::Process+0x97(unhandledMsgOut=0x31f958) in templeplus (0x0031f8e0)
  13 0x0081add6 GameLoop::Run+0x325() in templeplus (0x0031f990)
  14 0x0084ad1c TempleMain+0x39b(hInstance=0x400000, commandLine=0x31fec8) in templeplus (0x0031fe54)
  15 0x00829671 WinMain+0x290(hInstance=0x400000, hPrevInstance=(nil), lpCmdLine="", showCmd=0xa) in templeplus (0x0031fee4)
  16 0x00883a50 __scrt_common_main_seh+0xf7() in templeplus (0x0031ff30)
  17 0x7b62e280 EntryPoint+0xffffffff() in kernel32 (0x0031ff48)
  18 0x7bc5bb87 EntryPoint+0xffffffff() in ntdll (0x0031ff5c)
  19 0x7bc5bde0 EntryPoint+0xffffffff() in ntdll (0x0031ffec)
0x006cb841 GameObjectBody::ValidateFieldForType+0x11 in templeplus: pushl       0x0(%edi)
```

**Comment by DudeMcDude** [comment]
Finally got around to looking at this (sorry for the delay).
I saw two errors that caused crashes here:
1. A Lacedon had a missing item. Very strange, since as far as I know Lacedons don't have any inventory. My guess would be that it's a spell object, possibly from some Co8 added spell - do you happen to remember if you cast anything like that on them?
Also, do you have a save from after killing the Lacedons but before killing Grank's men?
2. Xan has a Chain Devil helmet, which triggered another exception. Did you actually obtain such a helmet?

**Comment by uralets** [comment]
В Пт, 14/05/2021 в 07:13 -0700, Dude McDude пишет:
> Finally got around to looking at this (sorry for the delay).

No problem! Thank you kindly for even working on this poor game)
Anyway I think I'm nearing the end of my involvement with ToEE (purely
as a player at least)..


> I saw two errors that caused crashes here:
> 
> A Lacedon had a missing item. Very strange, since as far as I know
> Lacedons don't have any inventory. My guess would be that it's a
> spell object, possibly from some Co8 added spell - do you happen to
> remember if you cast anything like that on them?
Interesting.. I'd never thought it could be something like this.
Thought it must have had something to do with overly long crafted item
name.
Nope, unfortunately I can't say if I did cast a specific spell, too
much time has passed.

> Xan has a Chain Devil helmet, which triggered another exception. Did
> you actually obtain such a helmet?
Yeah, think I got it from the ground at the Imeryds Run.

Damn this game is choke full of strange bugs. Atari must have had some
cheek to release it commercially back then.

**Comment by DudeMcDude** [comment]
> В Пт, 14/05/2021 в 07:13 -0700, Dude McDude пишет:
> Finally got around to looking at this (sorry for the delay).
> No problem! Thank you kindly for even working on this poor game) Anyway I think I'm nearing the end of my involvement with ToEE (purely as a player at least)..
> I saw two errors that caused crashes here: A Lacedon had a missing item. Very strange, since as far as I know Lacedons don't have any inventory. My guess would be that it's a spell object, possibly from some Co8 added spell - do you happen to remember if you cast anything like that on them?
> Interesting.. I'd never thought it could be something like this. Thought it must have had something to do with overly long crafted item name. Nope, unfortunately I can't say if I did cast a specific spell, too much time has passed.

Oh well. Next version will also log historical info on all casted spells in the save so I'll have that info.

> Xan has a Chain Devil helmet, which triggered another exception. Did you actually obtain such a helmet?
> Yeah, think I got it from the ground at the Imeryds Run. Damn this game is choke full of strange bugs. Atari must have had some cheek to release it commercially back then.

Well the chain devil helmet is actually by Co8. And the game crashing because of bad material reference is only with newAnimSystem = true, but it's false by default so I guess that's why you haven't tripped it. Eventually we'll enable it :) We'll also handle such cases by loading a bright pink texture instead of missing materials.

**Comment by uralets** [comment]
В Вс, 16/05/2021 в 01:34 -0700, Dude McDude пишет:
> > 
> 
> Oh well. Next version will also log historical info on all casted
> spells in the save so I'll have that info.
> 
Sorry I've long since overwritten it.
Also had to start over from a hard save point which I luckily had, bc
my Autosave became overwritten by an accidental click on the Tutorial
in the menu... Something to consider?

> > 
> 
> Well the chain devil helmet is actually by Co8. And the game crashing
> because of bad material reference is only with newAnimSystem = true,
> but it's false by default so I guess that's why you haven't tripped
> it. Eventually we'll enable it :) We'll also handle such cases by
> loading a bright pink texture instead of missing materials.
> 

Yes I know it's by Co8. The point re bugs still stands though.

Thanks again for you hard work on this flawed gem. Just wish there was
*a game* to go with all the potential...

**Comment by DudeMcDude** [comment]
> В Вс, 16/05/2021 в 01:34 -0700, Dude McDude пишет:
> > Oh well. Next version will also log historical info on all casted spells in the save so I'll have that info.
> Sorry I've long since overwritten it. Also had to start over from a hard save point which I luckily had, bc my Autosave became overwritten by an accidental click on the Tutorial in the menu... Something to consider?

Good point!
BTW I'm pretty sure it's Jaer's spheres of fire, your sorc has two of those (you get 3 I think) and I was able to reproduce it by throwing them at a critter, saving and loading.

> > Well the chain devil helmet is actually by Co8. And the game crashing because of bad material reference is only with newAnimSystem = true, but it's false by default so I guess that's why you haven't tripped it. Eventually we'll enable it :) We'll also handle such cases by loading a bright pink texture instead of missing materials.
> Yes I know it's by Co8. The point re bugs still stands though. Thanks again for you hard work on this flawed gem. Just wish there was *a game* to go with all the potential...

Me too. That's more or less why I started modding this particular game, actually - all the other games I've enjoyed felt complete enough, but this one... it had this feeling of tremendous unrealized potential.

**Comment by uralets** [comment]
> Me too. That's more or less why I started modding this particular
> game, actually - all the other games I've enjoyed felt complete
> enough, but this one... it had this feeling of tremendous unrealized
> potential.
> 
> 

Unfortunately the more I've played it the more I became convinced it
can't be fixed or modded into something pristine. It needs a complete
doing over. It's just plain unfinished in pretty much every respect.
Question is if it's worth it.
