### ISSUE TITLE
Visual Studio 16.9.4 dependency rebuild 

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#477]
Error when building T+ with new VS 16.9.4 Community Edition:
'..TemplePlus\dependencies\lib\python27.lib' was created by a different version of the compiler than other objects like '..\TemplePlus\Release\EASTL.lib'; rebuild all objects and libraries with the same compiler.

@shartte FYI

**Comment by shartte** [comment]
Booooooooooooooooooooooo we should disable interprocedural optimizations :-D

But yeah ok ok

**Comment by shartte** [comment]
My apologies, I totally forgot about it. Working on it now.

**Comment by shartte** [comment]
Alright, made a new release of the dependencies rebuilt using the latest Visual Studio on Github:
https://github.com/GrognardsFromHell/Dependencies/releases/tag/v1.8
