### ISSUE TITLE
Support for monster hit dice draining

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#485]
Many years ago, I tried to get the enervation and energy drain spells working, but there was a fatal flaw in the engine that made them too powerful for player use. Essentially, the game will kill a creature if its (temporary) negative levels meet or exceed its _class_ levels. However, most creatures don't have any class levels, so the spell will instant kill even e.g. balors.

Instead, monster hit dice should be taken into account. Balors have 20 hit dice, so it should require draining at least 20 levels to kill them.

I did a little testing and it seems the bug is still in effect. So, this is a vanilla bug that could conceivably be fixed, although not a very visible one since the spells that would be fixed just don't exist yet (for obvious reasons).

**Comment by DudeMcDude** [comment]
Hi Dolio! It's good to see you back.

It should be easy to fix I reckon. I'll have a look.

**Comment by dolio** [comment]
Wow, I'm impressed. I figured it would take a lot longer than that to fix. :)

Is there somewhere to get automatic built executables (e.g. the zip version from the release)? I suspect it'd be difficult for me to build it myself because I actually run the game in wine on linux, and doing a visual studio build inside wine seems like it'd be a ton of work, if it can even be done.

Maybe github already does this. I sometimes find it difficult to find things just by browsing its interface.
