### ISSUE TITLE
Dying with negative levels doesn't (always) kill you

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#494]
Here's another problem I discovered on the path to making Enervation work.

For some reason, killing someone that has negative levels doesn't always work, whether it is by giving them enough negative levels to kill them, or just damaging them once they have negative levels. The easiest way to see what's going on seem to be to give party members negative levels with, e.g.:

    game.party[0].condition_add_with_args('Temp Negative Level', 1, 1, 1)

If you give enough negative levels, and the character has more than 5HP per level, they will eventually 'die.' Then all the negative levels will disappear and they'll be reset to an HP of `5*NL-10`, where  `NL` is the number of negative levels they had when they died. This may mean they're actually alive again, or just dying at -5 in the case of a single negative level (still not strictly dead; they may stabilize).

However, from that point on, no amount of negative levels will kill them unless it gets their HP to negatives. You can set the character's HP to 150, and it will take 31 negative levels for them to be dying again. I'm not really sure why this is; they must be in some weird state from getting killed the first time.

I did a fair amount of testing, and your previous negative level fix seems to be unrelated to this behavior. I can reproduce it in 1.0.84. The fix with monster hit dice just means it _also_ happens on e.g. the giant and bear.

Oh, I think this also happens with `'Perm Negative Level'`, since those act pretty similar to temp levels in ToEE. I didn't test those as extensively, though.

**Comment by DudeMcDude** [comment]
Oh, I guess it’s because temp negative levels clear themselves when you die. So the easiest solution is to disable that. This begs the question: does resurrection clear negative levels?

**Comment by dolio** [comment]
The books don't really spell out what happens, either, and I can't find a definitive ruling.

Raise dead/resurrection is actually supposed to lower your level. And restoration is unable to fix that, but I'm not sure ToEE has any way to implement this.

It's also a little unclear just what each different concept is supposed to be. Enervation/energy drain give negative levels (which are "temporary"), but after one day you're supposed to save, and you either heal or actually lose a level. Enervation actually can't do that, because the negative levels should disappear after at most 15 hours, so they never induce the save-or-lose-level condition.

However, I think ToEE's temp negative levels just have you save every day until they disappear. I guess that could be fixed similarly to the other fix, but I don't know if there's a way to remove a level of a character. I think maybe a 'permanent' negative level in ToEE is supposed to be like losing a level? (P&P) Restoration gets rid of all (temporary) negative levels, and gives you experience to gain back one lost level per casting (except if it was lost from raise dead/resurrection), so that would explain why it can get rid of 'permanent' negative levels (except I'm not sure how you get those, since temp negative levels never become perm ones).

I think most of these subtleties aren't that important for ToEE, and mostly the short-term consequences matter. Energy drained people just getting back up in a fight is a lot more of a problem than all the long term restoration rules.

In that sense, I think resurrection/raise dead clearing temp negative levels is probably fine. If your character got weakened and killed, the resurrection is probably enough of a cost. Maybe it shouldn't clear permanent negative levels, depending on how you get those.

**Comment by dolio** [comment]
Incidentally ToEE almost matches the Pathfinder rules for negative levels. It has temporary and permanent negative levels, temporary negative levels let you save once a day to remove them (although lots of stuff overrides this), and restoration can remove the permanent ones.

Pathfinder also says that to raise someone killed by permanent negative levels, you must cast restoration on them right away afterwards. However, it says nothing about raising someone killed by temporary negative levels. Since they're easier to get rid of, perhaps they're intended to just go away in that scenario.

**Comment by DudeMcDude** [comment]
FYI, the meaning of the args in Temp Negative Level:

```
game.party[0].condition_add_with_args('Temp Negative Level', arg0, arg1, arg2)  
  arg0 - which class is affected (this is automatically set to highest class level by the engine)  
  arg1 - DC for permanent negative level saving throw  
  arg2 - inventory slot for the item which causes the effect (relevant only for the Holy/Unholy etc weapons )  
```

I'm going to go ahead and cancel the removal on death. Otherwise it could get too complicated I think.

**Comment by dolio** [comment]
Apologies for adding another comment to a closed issue, but I've fiddled around more, and wanted to correct inaccuracies in my description above in case someone happens across it.

1. I was remembering the behavior of temp negative levels backwards in ToEE. They actually never go away until you _fail_ the saving throw and they become permanent. I thought maybe this could be related to your `arg2` description above, since it seems like a temp negative level from an opposite aligned item shouldn't go away until you remove it. But I no `arg2` I've tried allows the level to be cleared on a successful save (0,1,2,-1,3000,100,...).
2. ToEE treats a permanent negative level like a temp negative level with respect to penalties (i.e. it doesn't try to roll back your actual levels, which is probably wise). However, it _does_ deduct experience each time you get a perm negative level. Then restoration gives you back experience when removing a perm negative level presumably. However, you can also get rid of perm negative levels just by gaining the experience (at least, the `levelup` cheat clears perm negative levels in that way).
