### ISSUE TITLE
Crash on projectiles

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#499]
With the new fix to particles, I'm getting crashes on spells with projectiles.

Removing the lines that apply particle effects to the projectiles from the spell script doesn't seem to fix the problem, so it seems to be something wrong with the projectiles themselves.

I suppose this could be a Wine problem, but projectiles were working fine before. I can attach a dump/log/save if desired.

**Comment by DudeMcDude** [comment]
Not related to particles fix :)
I recently replaced some funcs related to Touch Attack handling, because @Sagenlicht was trying to replicate Produce Flame behavior but apparently it's semi hardcoded.
