### ISSUE TITLE
Oversized two weapon fighting not showing in character sheet

### ISSUE THREAD

**Issue by valepu** [GrognardsFromHell/TemplePlus#535]
I am using 2 one-handed weapons with my character but In the statistics i see a -4 penalty rather than a -2

I found this merge request https://github.com/GrognardsFromHell/TemplePlus/pull/402 Where it says "Now Oversized Two-Weapon Fighting only applies to full attacks" but it should always apply. The feat description says

> When wielding a one-handed weapon in your off hand, you take penalties for fighting with two weapons as if you were wielding a light weapon in your off hand (see page 160 of the Player's Handbook).

To me this sounds like it should always work, even on single attacks made with either weapon

At the moment i'm using version v1.0.84

**Comment by doug1234** [comment]
I will take another look at this.  Was this on the character sheet or in the roll history.

**Comment by valepu** [comment]
Ok first of all let me say i'm sorry for saying something inaccurate about the single attack, i forgot you don't get any penalty when doing a single attack.

That said, I confirm the issue appears only in the character sheet 

![Screenshot from 2021-07-14 15-20-13](https://user-images.githubusercontent.com/5619832/125629123-f127398d-4953-4241-b135-7d5cb2f5574f.png)
![Screenshot from 2021-07-14 15-20-42](https://user-images.githubusercontent.com/5619832/125629134-13e7fc6e-b853-43c8-805e-a2ed76b1aade.png)

**Comment by doug1234** [comment]
Thanks for the additional info.  I have a pull request in that should fix the issue.
