### ISSUE TITLE
Can't compile as Release (Debug works)

### ISSUE THREAD

**Issue by valepu** [GrognardsFromHell/TemplePlus#543]
Hi,
Whenever i try to compile TemplePlus with Release Configuration I get this error

> 5>LINK : fatal error C1047: The object or library file '...\TemplePlus\Release\\EASTL.lib' was created with an older compiler than other objects; rebuild old objects and libraries

But when i build using Debug configuration it works fine. 
I am no expert of Visual Studio so i have no idea on where to check (is it normal to have that double "\" in the path?)

**Comment by shartte** [comment]
Are you on the latest Visual Studio 2019 version?
Can you say which version you are running?

**Comment by valepu** [comment]
From the "About" window i see this:

Microsoft Visual Studio Community 2019
Version 16.6.5

I haven't opened it in months so it's very likely i'm not on the last version, i'll try updating it meanwhile

**Comment by shartte** [comment]
Alright that might be it.

We are using Link-Time-Code-Generation for the pre-compiled dependencies package, which sadly means it's tied to a specific compiler version.

**Comment by valepu** [comment]
it worked! Thanks
