### ISSUE TITLE
Make characters walk instead of run for short distances

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#55]
And make it optional because some of us are speed maniacs like yours truly :)

**Comment by Shais2304** [comment]
http://www.co8.org/forum/showthread.php?t=11554

**Comment by DudeMcDude** [comment]
Added configurable Walk Distance in v1.0.60.

**Comment by sevdestruct** [comment]
Nice! Happy to see this finally added, thanks @DudeMcDude, I remember requesting/asking about something similar a while back, maybe that was via moddb though…
