### ISSUE TITLE
`ET_OnD20PythonActionCheck` dispatches on (possibly) the wrong value

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#551]
I've been fiddling around with python actions, using e.g. Divine Spell Power as a reference.

It seems most things with an action check expect to dispatch using the action enum as a key. However, the dispatcher uses the d20action's `data1` as the key. This means, for instance, you never run out of Divine Spell Power uses, since it sets the `data1` to `0` in the radial menu. I think death arrow probably has the same problem. Maybe others.

**Comment by DudeMcDude** [comment]
Probably related to 5d514d1 (whose purpose was to free up data1). I vageuly recall modifying some python scripts and telling @Sagenlicht and @doug1234 to watch out for oversights, but I can’t find any trace of that now...

**Comment by Sagenlicht** [comment]
data1 was indeed freed up and I do use it in the Marshal class to pass the aura id in data1:
auraRadialId = tpdp.RadialMenuEntryPythonAction("Activate {}".format(auraName), D20A_PYTHON_ACTION, pythonActionToggleAuraId, **auraEnum**, "TAG_CLASS_FEATURES_MARSHAL_MINOR_AURAS")

Do I understand you correctly, that e.g. divine_spell_power.py would be fixed if you simply change the data1 field from 0 to the  action enum key?

Change
> radialAction = tpdp.RadialMenuEntryPythonAction(-1, D20A_PYTHON_ACTION, divineSpellPowerEnum, 0, "TAG_INTERFACE_HELP")

to
> radialAction = tpdp.RadialMenuEntryPythonAction(-1, D20A_PYTHON_ACTION, divineSpellPowerEnum, divineSpellPowerEnum, "TAG_INTERFACE_HELP")

if so I can volunteer to change the feats

**Comment by DudeMcDude** [comment]
Ah no, looks like it should be fixed in the engine here:

https://github.com/GrognardsFromHell/TemplePlus/blob/7e3c6da890de345d948998ffea28c27f54a59714/TemplePlus/d20.cpp#L2221
