### ISSUE TITLE
Newly created monks get a level 1 bonus feat

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#555]
I was going to fix the class script, but it occurred to me that there might be a better way than I can think of to fix the problem.

It appears that the issue is that the character creator sets the chosen class level to 1 before the feat chooser tab. So, it's impossible to distinguish between choosing feats at level 1 in the character creator and choosing feats at level 2 on the level up screen just by testing the class level. So the monk logic lets you pick level 2 bonus feats at level 1 (*and* level 2). It's possible some other classes are affected; fighter would be, but they get bonus feats at both levels anyway.

The way I came up with to figure it out was to test if the character is at 0 experience. But maybe it's preferable to change something else, I'm not sure.

Edit: Oh, and I'm aware that P&P monks do get a bonus feat at level 1, but ToEE doesn't have improved grapple, so it's locked to stunning fist.

**Comment by DudeMcDude** [comment]
That could work, but actually we have a flag indicating new character, just need to expose it to python.
I thought the API could also handle that though, need to look it over. Maybe with spells.

**Comment by DudeMcDude** [comment]
We ran into a similar problem with feat requirements. The solution is to use char_editor.stat_level_get instead of obj.stat_level_get.

**Comment by DudeMcDude** [comment]
Fixed 0e332d7c7c8ac8b0596a8658adcdf14bc64708b0
