### ISSUE TITLE
S_Spell_Cast weirdness

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#577]
@dolio @Sagenlicht @doug1234
I noticed a bug with the S_Spell_Cast signal for touch spells - it triggers spell removal when you are the *target* of a spell too. E.g. Produce Flame will go away if someone casts a spell on you.

I vaguely recall we ran into a situation where we relied on S_Spell_Cast signal for something (probably for ending spell / concentration). And possibly this very same bug, perhaps it was corrected in the python in one of the new spells? Not sure.

Either way I'm changing the behavior of remove_spell and remove_spell_mod to check that the dispatch caller is the same as the spell caster in case of DK_SIG_Spell_Cast. As far as I can tell this event is only used for touch spells anyway (for cancelling the charge if you cast another spell). I'm not sure why it also dispatches the event for spell targets, but I'll leave that be.

If anyone thinks of situations where this could screw things up, let me know.

**Comment by Sagenlicht** [comment]
If I remember correctly, @dolio had this issue while doing the touch spell handler in the spell_utils

**Comment by DudeMcDude** [comment]
Yes, unfortunately it looks like you can't distinguish it at the level of remove_spell / remove_spell_mod. Unfortunately they directly use these callbacks for most of S_Spell_Cast, and only wrap it with some logic for Spike Stones. I guess I'll have to batch replace the hooks with a wrapper rather than rewrite the function itself.

**Comment by DudeMcDude** [comment]
Fixed by b1e668d37edae733ddef3b54351359f56669eb9b
