### ISSUE TITLE
Mouse Movement Stuttering

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#587]
So, this seems like it could easily be a Wine-related problem, but I thought I'd report it anyway in case someone can reproduce it on Windows.

It seems like mouse movement sometimes causes the rendering to lag. I think it is more severe with faster mouse movement. If you move the mouse slowly, the animation will be smooth, but if you move the mouse quickly, the whole scene will stop rendering briefly, like everything is blocked on some kind of mouse position update.

However, I've also noticed that this does not occur if something like the inventory window is popped up. So whatever event/etc. is blocked by mouse movement runs more consistently while a window is open. I think this even happens on the title screen. if you wave the mouse around it can lag the temple flame animation, but getting to the character creation window alleviates the problem.

This also doesn't seem to be a problem with the original exe, but it affects T+ 1.0.84.

Sorry this is so vague. Graphics isn't really my forte.

**Comment by DudeMcDude** [comment]
Does the logfile provide any hints?

I'd have guessed it pathfinding related, but then you said it happens on the title screen too.

**Comment by dolio** [comment]
Actually, I think I'm going to close this, because I think my system may have been in a weird state. I can't reproduce it after a(n unrelated) restart. Possibly some weirdness caused by libraries being updated without the running kernel matching or something. If it starts happening again I'll look in the logs.

Sorry about the noise.

**Comment by shartte** [comment]
Hmmmmmm. Dunno about the logfiles.
I can look out for this on OT as well, there are certainly some areas where our DX11 renderer certainly isn't really optimal, especially when it comes to text rendering.

Do you have the ability to run "perf record" against a wine binary? I have no idea, tbh.
