### ISSUE TITLE
New greybar code sometimes skips attacks

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#589]
I've done a little more testing, and it seems like the attack skipping issue is relatively new. I fought some battles on build 2963 and didn't see any skips. Then back to 2993 and saw skips. I'm attaching [a log](https://github.com/GrognardsFromHell/TemplePlus/files/7026537/bad.log) grabbed from just after it happened. The 'Erika' character mentioned in the debug messages had just done the critical animation, but no hit occurred.

**Comment by DudeMcDude** [comment]
Yeah the greybar thing caises some fubars. Will push a fox.

**Comment by DudeMcDude** [comment]
Pushed. Let me know if it solves the issues.

**Comment by DudeMcDude** [comment]
@dolio ping

**Comment by dolio** [comment]
Definitely seems better. Haven't noticed any dropped attacks since switching.

**Comment by DudeMcDude** [comment]
Ok, closing it until further notice
