### ISSUE TITLE
StartMap variable

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#599]
Question - how this variable is being set? I searched in temple.dll (via IDA) and Temple+ - no indication how it is assigned.

**Comment by shartte** [comment]
You could check in OpenTemple if you want. I think it's hardcoded though

anatoliy-savchak ***@***.***> schrieb am So., 29. Aug. 2021,
13:04:

**Comment by anatoliy-savchak** [comment]
> You could check in OpenTemple if you want. I think it's hardcoded though

I checked. Yep indeed hard-coded. Would be nice to allow via settings somehow.

**Comment by DudeMcDude** [comment]
I thought the modern approach was to use the shopmap as entry point ;)

**Comment by anatoliy-savchak** [comment]
Sure. But I wanted to have map 5001 as ShopMap, not 5107

**Comment by DudeMcDude** [comment]
Isn't that the hommlet map? It has a bunch of worldmap hard coded stuff associated with it. Or do you need that?

**Comment by anatoliy-savchak** [comment]
Oh, thanks for letting me know! I just wanted this to be clean for new modules.
Essentially I reworked co8 shop map to default Shop Map for my zmod modules.

But still I'd like startMap to be configurable. For example 5002 then.

**Comment by anatoliy-savchak** [comment]
I would love to have ability to set game.start_map = 5002 in Startup.txt. 
Plus bunch of other things, like setting limitations in character creation dialogs.

Is it possible?

**Comment by DudeMcDude** [comment]
I suppose. Just be aware that in principle start map is actually an array that depends on party alignment.

More generally, you could hook the start adventure button to run a script, and then do whatever you want there (teleport to map or whatever).

**Comment by anatoliy-savchak** [comment]
> Just be aware that in principle start map is actually an array that depends on party alignment.

Start Map is almost always Shop Map :). Otherwise it could be real map, for example IWD2 PC starts with nothing at all (robes and staff).

> More generally, you could hook the start adventure button to run a script, and then do whatever you want there (teleport to map or whatever).

Sure. But what about loading a save?

I like Main Menu startup, as I could potentially even check for module's updates and notify a user. Set up requirements of zmod for a module (I really need min max of abilities). Or whatever.

**Comment by DudeMcDude** [comment]
> > Just be aware that in principle start map is actually an array that depends on party alignment.
> 
> Start Map is almost always Shop Map :). Otherwise it could be real map, for example IWD2 PC starts with nothing at all (robes and staff).

That's ok, just noting that in principle ToEE has 9 different starting maps per alignment. You can make it set the value for all of them of course.

> 
> > More generally, you could hook the start adventure button to run a script, and then do whatever you want there (teleport to map or whatever).
> 
> Sure. But what about loading a save?

What about it?

> 
> I like Main Menu startup, as I could potentially even check for module's updates and notify a user. Set up requirements of zmod for a module (I really need min max of abilities). Or whatever.

Yes, I know you love your scripts ;)
The other thing I had to remark about this is that you'll probably run into an issue / need of externalizing ALL the map properties, like which Area is which, and how they're assigned to worldmap icons. I started doing this in a branch, basically for the IE expansions, but decided to leave it to Open Temple because it's a lot of work that I'd rather do there.

**Comment by anatoliy-savchak** [comment]
OK, let's clos it for now. Personally I do not see fast and elegant solution. Moreover issue is not critical nor important.
Thanks!

**Comment by anatoliy-savchak** [comment]
I see it got implemented, thank you Sir!!! :)

https://github.com/GrognardsFromHell/TemplePlus/commit/57b1832ca314182e049b71d0943e333b4aa0dba8
