### ISSUE TITLE
Icon corruption when dragging portraits

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#60]

**Comment by DudeMcDude** [comment]
ping :)

Small but annoying glitch

**Comment by shartte** [comment]
Uhm okay. I will look into it.

**Comment by shartte** [comment]
Also added proper hotspots for the map grab cursor and the slider cursor. It's a dirty filename based hack but there are no properties associated with the cursors other than the filename. So that's the only thing I can use.
