### ISSUE TITLE
Touch of Fatigue issues

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#600]
Reported by a user on the RPGCodex:

Touch of fatigue doesn't allow a saving throw as it should, only an attack roll. It also allows the caster to move, attack, and move again without feats.

I have this vague recollection I already reported this, but I can't find it. Maybe it was something else.

**Comment by doug1234** [comment]
Should have time to look into this one sometime this week.

**Comment by dolio** [comment]
Where is that spell from? The writeups I can find online don't have a saving throw, but they're all pathfinder.

**Comment by doug1234** [comment]
https://www.d20srd.org/srd/spells/touchOfFatigue.htm

**Comment by dolio** [comment]
Oh, duh, okay. :)
