### ISSUE TITLE
ChooseRandomSpellFromList  - spell range issue

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#610]
In Orc Cave of IWD there is Orc Shaman, AI of whos is using this ChooseRandomSpellFromList way of determining of spell selection.

What I have seen in my playthroughs:

Shaman would use Sound Burst even if Shaman is way too far to be within a range of the spell. I saw same thing in ToEE.

split from #602

**Comment by DudeMcDude** [comment]
BTW, are you sure it's ChooseRandomSpellFromList? And if so, why does it matter?

**Comment by DudeMcDude** [comment]
@anatoliy-savchak ping

**Comment by anatoliy-savchak** [comment]
>BTW, are you sure it's ChooseRandomSpellFromList? And if so, why does it matter?

ChooseRandomSpellFromList will go before AI tactics. That's why I always disable it zmod.

**Comment by anatoliy-savchak** [comment]
Verified, now it works good. Closing the ticket.

**Comment by DudeMcDude** [comment]
That's odd, because I didn't touch ChooseRandomSpellFromList 🤨 
Unless the issue wasn't there, which as far as I know it isn't...

**Comment by anatoliy-savchak** [comment]
Shaman had problems finding correct (long) path my PC, so in both situations (before and today) he would stay around the corner. But in first situation he would still cast Sound Burst and it would work through the walls. Now he as not Sound Bursting my players unless they would PC approach him so it worked fine.

That it why I thought it is closed.

**Comment by DudeMcDude** [comment]
Well I did change cast area and cast fireball tactics so that's probably why.
