### ISSUE TITLE
ToEE Co8 - item_insert hooks unsupported field

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#611]
Minor issue

I spotted bunch of unsupported access field messages. Apparently there are many item_insert events fired when my script was inserting items like Longbow into a container so such scripts like 281, 282 186 are run with supposition that only critter could be triggerer.

**Comment by DudeMcDude** [comment]
Can you provide more detail? Or are you going to look into this yourself?

**Comment by anatoliy-savchak** [comment]
> Or are you going to look into this yourself?

Yes, I will.

Log:
![image](https://user-images.githubusercontent.com/40269424/132660542-3355405a-e78d-432f-901b-48dae75132e1.png)

insert_item in protos:
![image](https://user-images.githubusercontent.com/40269424/132660763-820162f9-cdfc-4441-9baf-e70855f6c767.png)

Reason: obj.has_feat
![image](https://user-images.githubusercontent.com/40269424/132660870-87b8ed48-8a98-4a4e-adef-0ec67be024b1.png)

Ways to fix this:
1. Fix has_feat to check if obj is appropriate type (npc or pc).
2. Modify all insert_item hooks and check for tiuggerer type;

**Comment by DudeMcDude** [comment]
By 2. You mean the scripts such as that?
I think it's good to fix them. You can fix has_feat as well but it should still emit a warning, who knows what other bugs this can catch.

**Comment by anatoliy-savchak** [comment]
Actually I see this event EvtObjRangeIncrementBonus, so would be better to add this feat_far_shot bonus via modifier. And remove these hacks completely.

**Comment by anatoliy-savchak** [comment]
I'm considering to add PyObjHandle.is_throwing_weapon(), what do you say @DudeMcDude?

**Comment by DudeMcDude** [comment]
> Actually I see this event EvtObjRangeIncrementBonus, so would be better to add this feat_far_shot bonus via modifier. And remove these hacks completely.

I agree, this sort of hack is not necessary anymore...

**Comment by DudeMcDude** [comment]
> I'm considering to add PyObjHandle.is_throwing_weapon(), what do you say @DudeMcDude?

Sure, go ahead
