### ISSUE TITLE
rules bug - Total Defense allows AOO and Fighting Defensively

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#612]
Total Defense should not allow AOO.

![image](https://user-images.githubusercontent.com/40269424/132662355-829fe51d-f876-45b6-b65f-edee036d360f.png)

Fighting Defensively is combined in AC, it should not.
![image](https://user-images.githubusercontent.com/40269424/132662559-950f25e6-1aed-4889-8225-7d0eb6e4f661.png)

Also as a side note - we should check for bonus in Total Defense when Tumble is 5 or more Ranks. Plus Two Weapon Defense has bonus as well.

![image](https://user-images.githubusercontent.com/40269424/132662882-03e89aa5-2717-4aeb-bb17-96ca64ec325a.png)
![image](https://user-images.githubusercontent.com/40269424/132662907-68960519-42af-443e-b163-12b404c263c4.png)

**Comment by dolio** [comment]
How were you able to use total defense and fighting defensively in the same round? Did the AoO trigger fighting defensively? That probably shouldn't happen.

The tumble synergy bonuses work.

**Comment by anatoliy-savchak** [comment]
>How were you able to use total defense and fighting defensively in the same round?

I'm surprised as well. I was using IWD module, so no zmod intervention.

AOO should work in FD mode. But should not work in TD.

Total Defense does not have any specific code for AOO prevention:
![image](https://user-images.githubusercontent.com/40269424/132733535-30990a32-1ec8-40e8-aa8e-77b21b42a1c3.png)

TD has Tumble bonus - true.

Fighting Defensively should reset "checked" state (although "charged" I like more) on Begin Round. No idea how did it happen.
![image](https://user-images.githubusercontent.com/40269424/132733794-fa6cd4f0-e1ac-4e50-80c1-0e763921f18e.png)

FD has Tumble bonus, confirmed as well.

**Comment by dolio** [comment]
What I mean is, you need to make an attack during your turn to fight defensively. Just having the 'Fight Defensively' box checked shouldn't make an AoO give you the AC bonus, which might be how it happened in your example, if AoOs can still happen during total defense.

E.G. if you have 'Fight Defensively' on, and have combat reflexes and uncanny dodge, an opponent running past you and provoking an AoO shouldn't increase your AC before you even take a turn.

**Comment by anatoliy-savchak** [comment]
> What I mean is, you need to make an attack during your turn to fight defensively.

Yeah, that's in dispTypeBeginRound row in the conditionFightDefensively. Very strange.

**Comment by DudeMcDude** [comment]
I was able to reproduce this with an AoO.
The signal for FD is based on ATTACK_MADE, which also can also occur during an AoO...

**Comment by anatoliy-savchak** [comment]
How about sending D20CAF flags into EventObjD20Signal.data2? 
with d20Sys.d20SendSignal(attacker, DK_SIG_Attack_Made, (int)&evtObjDam, 0);

**Comment by anatoliy-savchak** [comment]
I also would like to propose the following extension to fighting_defensively.py:
1. Add python query: "Fighting Defensively Charged" to get arg 1 (attack made);
2. Add python query: "Fighting Defensively Charge" to set arg 1 to 1
3. Add python query: "Fighting Defensively Uncharge" to set arg 1 to 0
4. Add python query: "Fighting Defensively Check" to set arg 0 to 1
5. Add python query: "Fighting Defensively Uncheck" to set arg 0 to 0

This would satisfy following:
1. In Total Defense on Condition Add we would send "Fighting Defensively Uncharge";
2. I could control monsters AI to set them FD via sending "Fighting Defensively Check";

**Comment by DudeMcDude** [comment]
Largely ok, except:

* Set -> via signal not query. 
* No need for two methods for each arg, just d20_send_signal(key,value), similar to Casting Defensively and Power Attack.
* Total Defense on Condition Add: what is this supposed to solve? The above bug occurs when you make an AoO - it will add the "Charge" after this callback.  
I wanted to propose using the same bonus type, but they already do - dodge bonuses just stack :P Anyway adding the AoO possible query should prevent the above bug I think.

**Comment by anatoliy-savchak** [comment]
> Anyway adding the AoO possible query should prevent the above bug I think.

To TD - yes! :)

"Set" and signal "value" - yes, thank you.

As for AOO in FD - see my comment above. We should send D20CAF flags into EventObjD20Signal.data2. And hook \ rewrite TacticalOptionsAbusePrevention function to check if attack is AOO in that flags.

And indeed TD sending signal is not necessary, thanks!

**Comment by DudeMcDude** [comment]
You have the entire event object as arg already (which is better and more future proof than ad hocing a single value).

**Comment by anatoliy-savchak** [comment]
More information in [FB group](https://www.facebook.com/groups/1132508503876452/posts/1281803312280303/?comment_id=1282112032249431):

> As others said, it lasts until the start of the character's next turn, for both penalty to hit and bonus to AC.
On a side note, in PHB2, in the Shield Specialization feet tree, Active Shield Defense gives you some advantages when fighting defensively or using the total defense action:
"Benefit: When fighting defensively and using a shield, you do not take the standard ﬁghting defensively penalties on attacks of opportunity.
When using the total defense action and a shield, you still threaten the area around you as normal. You can make attacks of opportunity with a –4 penalty."
So if you want, you can build a character around the concept of being really hard to hit and getting attacks of opportunity. Not convinced it would be the best way to tank, but could be amusing...
The Cautious trait from UA gives you a +1 AC fighting defensively or using total defense, but you get a -1 to save vs fear, cannot take uf immune to fear.
Deadly Defense from Complete Scoundrel goes a different direction from the shield route:
"Beneft: When fghting defensively, you deal an extra 1d6 points of damage with any light weapon or with any weapon to which the Weapon Finesse feat applies (such as a rapier, spiked chain, or whip).
This feat’s beneft applies only when you are unarmored or wearing light armor and not using a shield.
Special: If you have the Combat Expertise feat, you also gain the beneft of Deadly Defense when taking a penalty of at least –2 on your attack roll from that feat."
Just a few random things I have given NPCs in my games related to defensive fighting...

**Comment by anatoliy-savchak** [comment]
Question to you Sitra - can we override or remove vanilla's dispatch hooks? I mean can we move FD and TD completely to Python?

**Comment by DudeMcDude** [comment]
IIRC if you just define it as a new modifier rather than extend existing it'll override the original.
However in this particular case i think the engine directly references the condstruct, so that'd need to be changed as well.

**Comment by doug1234** [comment]
Wouldn't just extending total defense to set the AOOPossible query return value to zero be enough to fix this?
