### ISSUE TITLE
Abjurant Champion meta-magic effect makes casting time full round

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#614]

**Comment by doug1234** [comment]
Very odd.  I will look into this one tomorrow.

**Comment by doug1234** [comment]
Looks like there was a bit of an update on this one:

*Edit: once the AbChamp reaches 2nd level, the Abjuration spells are correctly quickened for a wizard-based AbChamp. So the full round casting only occurs at lvl 1 for a wizard.
... However the sorcerer meta-magic behavior is full round casting for any meta-magic. The SorcAbChamp inherits this; After lvl2+ = SorcAbChamps are always full round casting for any Aburation spell.

(I should mention that iirc ages ago I tried using the Rapid Metamagic feat for sorcs and it didn't seem to work. So if looking at tweaking SorcAbChamps, the Rapid Metamagic feat might be worth looking at, as well. If it is not already fixed. )

**Comment by doug1234** [comment]
Looks like it is only an issue for level 1 abj champ that have the sorcerer base class.

**Comment by DudeMcDude** [comment]
I suppose you could replicate the code in rapid metamagic to correct that.
