### ISSUE TITLE
Debug build error (infrastructure)

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#623]
Debug build fails:
![image](https://user-images.githubusercontent.com/40269424/134815459-ae93888c-6f42-4fd9-afed-8f0dc76a276c.png)

But release works fine.

**Comment by shartte** [comment]
There was an update to the dependencies package a while ago. Unless we mistakenly published the deps incorrectly, but they are built automatically...

**Comment by anatoliy-savchak** [comment]
Hmm, it's not so simple.
Release does not build with v1.10:
![image](https://user-images.githubusercontent.com/40269424/134816739-22c32d05-ecb0-4937-bc94-28b44e46d09a.png)

But release works well with v1.9.
Debug works well with v1.10 but not with v1.9.

**Comment by DudeMcDude** [comment]
It works for me. You probably just need to clean the solution.
