### ISSUE TITLE
consider_target - Externalize numeric values to functions 

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#640]
`	if a_leader != OBJ_HANDLE_NULL:
		if a_leader.distance_to(target) > 50:
			if attacker.distance_to(target) > 50.0:
				return 0`

I need to affect these numbers. I propose to externalize them as functions, so I could easily hook them.

**Comment by DudeMcDude** [comment]
I prefer you just hook the function to suite your purposes. That is ultimately the most flexible thing to do, and I suspect you'll make good use of that.
