### ISSUE TITLE
Orb of Golden Death infinite Large Earth Elementals

### ISSUE THREAD

**Issue by zicion** [GrognardsFromHell/TemplePlus#682]
My orb of golden death has infinite Large Earth Elementals, i have no idea why, its was fun stomping the fire frogs with it though
![Screenshot 2022-07-10 003100](https://user-images.githubusercontent.com/74786857/178123319-4d858c0c-a76a-4294-874e-521c193429fa.png)
.

**Comment by doug1234** [comment]
A save file would be helpful for this one (templeplushelp@gmail.com).

**Comment by DudeMcDude** [comment]
Indeed a vanilla bug. Wonder if anyone else noticed this...
