### ISSUE TITLE
Tower shield doesn't apply -2 penalty to attack

### ISSUE THREAD

**Issue by zicion** [GrognardsFromHell/TemplePlus#685]

**Comment by doug1234** [comment]
Added pull request for adding the penalty but only with stricter rules enforcement on.  I think fixing this bug would annoy some players.

**Comment by zicion** [comment]
They just need to use a "shield broch" then.

**Comment by DudeMcDude** [comment]
Fixed in v1.0.86 (with Stricter Rules option)
