### ISSUE TITLE
Game crash on certain fights when playing with debug version

### ISSUE THREAD

**Issue by valepu** [GrognardsFromHell/TemplePlus#689]
Hi,
I am having an issue with certain fights (so far 2 fights: the ogre at the Moathouse and air elementals at the center of the -2 floor in the temple). When I play with the version built from source (following the instructions in this repo's readme, no more no less) at the end of the fight the game inevitably crashes with the error in this image. It seems specifically related to when the game is built for debug (doesn't matter if debug is active or not) because when I play with the release version installed from the repo those fights work fine. 
I wasn't able to build a release version myself, whenever I try I get an error saying python27.lib is built with a different version of the compiler than other libraries (that's with VS 2019)

It's worth mentioning I have the Co8 mod installed and active (I haven't tested if the issue happens with it disabled tho).

Let me know if there's something else I can provide

![debug-crash-1](https://user-images.githubusercontent.com/5619832/180625911-6b444e6f-ee25-4c2e-ab05-dd8ba3b182fe.PNG)

**Comment by DudeMcDude** [comment]
You probably have the wrong version of the dependencies. Which VS edition are you using?

**Comment by valepu** [comment]
Hi,
I have VS 2022 but I downloaded VS 2019 just so I could play Temple+ :)
The dependencies I downloaded are the latest https://github.com/GrognardsFromHell/Dependencies/releases/ (the one released 16 days ago), To make sure it's the correct dependencies I downloaded them again but the same thing happened

When I build using the debug configuration the build works and I can play (except in the fights I mentioned) when I build using the release configuration the build fails with the error shown at the end

![release-error-1](https://user-images.githubusercontent.com/5619832/180640280-bce760b6-3d42-42fb-a17a-2d62ea6fa96f.PNG)

I made no modification to the project after cloning it

**Comment by DudeMcDude** [comment]
Oh, the latest dependencies release is actually for VS22 :) for 2019 you'll want the one before that.

**Comment by valepu** [comment]
Ah I see! Maybe it's worth mentioning it in the readme

**Comment by valepu** [comment]
I opened the project with VS 2022, got a prompt to upgrade the compiler version, then built it using release configuration and it worked. Thanks!
