### ISSUE TITLE
Bardic music missing

### ISSUE THREAD

**Issue by dolio** [GrognardsFromHell/TemplePlus#755]
I'm not sure when this started happening, but it seems like if I create a bard character, they don't actually have bardic music in their radial. Gaining levels and resting doesn't seem to help. I have a somewhat old version of temple+ lying around and it happens there, too, so it doesn't seem like a recent issue. Also doesn't seem to be due to random stuff I've been working on.

The characters seem to have the condition/feat for bardic music, it's just not in the radial. Possibly the arguments to the condition are bad. I have an old save game with Zaxis. His music still works, and the sixth argument to his bardic music condition is non-zero. I'm unsure if that's actually a factor, though.

**Comment by doug1234** [comment]
That is really strange.  Someone on the co8 forum reported something similar but it couldn't be reproduced (https://co8.org/community/threads/new-temple-available.13049/page-27).  Do you think you have the same issue and can you send me the save game?

**Comment by dolio** [comment]
Yeah, it seems like the same issue. Not sure what the problem is.

Save game is attached, I think.

[music.zip](https://github.com/GrognardsFromHell/TemplePlus/files/14174526/music.zip)

**Comment by doug1234** [comment]
I couldn't load it.  I think it should have 4 files but there were only 2 in the zip.  Can you give ti another shot?

**Comment by dolio** [comment]
[music.zip](https://github.com/GrognardsFromHell/TemplePlus/files/14189194/music.zip)

Try this one.

**Comment by doug1234** [comment]
Looks like you don't have any ranks in preform.  It takes 3 for the menu to get displayed.  I leveled up and maxed out perform and the menu was displayed for me.

**Comment by dolio** [comment]
Oh, of course. I wonder if that was what was going on with the other person.

I guess that's the issue with just wanting to get through character creation as fast as possible.
