### ISSUE TITLE
import toee

### ISSUE THREAD

**Issue by anatoliy-savchak** [GrognardsFromHell/TemplePlus#779]
Recently I saw that to run a function in my Python script I have to do `import toee` first in the console.

But it wasn't like this before.

My modules depend on this badly, please fix.

**Comment by anatoliy-savchak** [comment]
It's not related to modules, so it's fine.

It is related to console. I cannot use these:
toee.game.leader
toee.obj_f_critter_feat_idx

**Comment by anatoliy-savchak** [comment]
When you type or want to execute function with parameter: toee.game.leader:

![image](https://github.com/GrognardsFromHell/TemplePlus/assets/40269424/e71b3e9f-d64c-4d11-9931-2cc9315df376)

**Comment by doug1234** [comment]
I think that change should fix the problem.
