### ISSUE TITLE
Console newline bug

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#80]
Ok this is really weird :P

http://i.imgur.com/DTN0z5T.png

What happens when you put a \n at the beginning and at the end of a print string ("\nOnSpellBeginRound\n" in this case)

But I guess we're not far from replacing the console outright?

**Comment by shartte** [comment]
Yeah I accidentally was removing the newline in the string and forgot that i actually was overwriting a string constant used by Python internally, since i was modifying the original and not a copy.

I now make a copy before i modify the string and it works much better.
