### ISSUE TITLE
Furnok's Skill Points at Level Up (Minor)

### ISSUE THREAD

**Issue by Legion50** [GrognardsFromHell/TemplePlus#804]
Furnok is receiving 1 more skill point at level up than he strictly should as a Rogue with 14 Intelligence.

8 for class + 2 for INT modifier = 10 skill points per level

But he's actually receiving 11 (or he was for me, anyway).

**Comment by dolio** [comment]
Furnok is human. Humans get 4 bonus skill points at level 1, and 1 bonus point at every subsequent level.

**Comment by Legion50** [comment]
...huh. When and how did I forget about that? Lol thanks!

**Comment by Legion50** [comment]
Wait a minute, if that's the case, doesn't he not have enough *spent* skill points? The reason I made this issue is because I had an extra skill point floating around at level up that I had to put somewhere. I'll check later.

**Comment by Legion50** [comment]
Yeah, if my math is right, he's being shorted an entire skill's worth of points!

8 (Rogue) + 2 (INT) + 1 (Human) = 11 per level (x4 = 44 at 1st level)

Furnok is level 4 when you recruit him. 44+11+11+11=77 points, but he has only **ten** skills with investment, each with 7 points. He's only spent 70 points, even though he should have spent 77!

Thoughts, @dolio ?

**Comment by dolio** [comment]
I think spent skill points are determined by his proto entry. So, it could be changed there, but someone would have to decide what extra skill he should have. Maybe there's an obvious choice, though.

Also, since he's level 4, someone would have to decide whether he just increased his intelligence last level, in which case he would have only one extra point.

**Comment by Legion50** [comment]
I was able to look up the original module the game was based on and he has the same stats as he did in the module at the same level (and I'm assuming 1e doesn't have the same rule where you can increase your stat points at level up), so... yeah. You're not _wrong_ that he would have, but I don't think the devs actually took that into consideration lol, they just copied and pasted the character.

Also, re: which skill, it doesn't help that NPCs in the party don't interact with other NPCs (or open chests, or use portals, or -). Maybe give him Appraise, since he's a treasure hunter? Idk.

**Comment by dolio** [comment]
BTW, I looked at Furnok's prototype, and there might be another issue. It kind of looks like he has the maximum number of skills filled in. So it might not actually be possible to give him more skills without some trick.
