### ISSUE TITLE
Static object bug (python related?)

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#98]
Bug reported at:
http://www.rpgcodex.net/forums/index.php?threads/templeplus-alpha-testing-thread.98897/#post-4073387

Not sure what exactly causes this, but it appears to be Python-replacement related, since it works ok up to appveyor build 117 (pre-Python replacement) and breaks on build 125 (post-Python replacement).

The script involved in this is py00225zthrone_controller.py:

def san_first_heartbeat( attachee, triggerer ):
	if (game.global_flags[341] == 1):
		for obj in game.obj_list_vicinity(attachee.location,OLC_SCENERY):
			if (obj.name == 1610):
				obj.object_flag_unset(OF_DONTDRAW)
			elif (obj.name == 1616):
				obj.destroy()
			elif (obj.name == 1617):
				obj.destroy()
		loc = location_from_axis( 489, 396 )
		throne = game.obj_create( 2090, loc )
		if (throne != OBJ_HANDLE_NULL):
			throne.rotation = 2.3561945
		attachee.destroy()
	return SKIP_DEFAULT

The bug is that the destroyed object re-appears and the objects that were "unset" (e.g. the name == 1610 one, which is the door icon) get reset. Assign this to mr. pug for input :)

**Comment by shartte** [comment]
Yeah I'll check it out. Could either be a swapped attachee / triggerer or
issues in object_flag_unset / destroy

**Comment by DudeMcDude** [comment]
Oh, I think I should clarify:
It works ok the first time you enter the map (that is, the objects that should be destroyed get destroyed, etc.)
The trouble is that when you re-enter the map, the objects get refreshed! Because otherwise obj.destroy() and obj.object_flag_set / unset seem to work fine.
I suspect it might be something more subtle, like order of execution compared to the creation of the cache in the game folder.

**Comment by shartte** [comment]
Huh but we didn't actually change anything about that... Odd
