### ISSUE TITLE
Game crashes when minimized

### ISSUE THREAD

**Issue by DudeMcDude** [GrognardsFromHell/TemplePlus#99]
When minimizing the game, it repeats the warning:

Direct3D Error @ mDevice->Present(nullptr, nullptr, nullptr, nullptr): S_PRESENT_OCCLUDED

(on every frame I think)

And crashes after about 3-4 minutes. UsingDirect3d9Ex is on.

Call Stack:
http://imgur.com/utsOxva

Edit: this does not happen when UsingDirect3d9Ex is FALSE.

**Comment by shartte** [comment]
Should be fixed now. We had to make *sure* that the framecounter got increased even for S_PRESENT_OCCLUDED, or otherwise it'd start reallocating all GPU buffers the subsequent frame.
